#!/usr/bin/env python
"""Aurora architecture CHANGELOG generator.

Reads `git log` of commits whose subject starts with a versioned tag like
`v78a:` / `v78b:` / `v78q:` etc. — the convention used for the AuroraIA-v2
multi-agent system evolution. Produces a Keep-A-Changelog-style markdown
file at `CHANGELOG.md` (repo root).

Usage:
    python .claude/hooks/gen_changelog.py            # write CHANGELOG.md
    python .claude/hooks/gen_changelog.py --stdout   # print to stdout
    python .claude/hooks/gen_changelog.py --check    # exit 1 if CHANGELOG drifted

The --check mode is meant for the self-test gate: it re-generates in memory
and compares to the committed CHANGELOG.md. If they differ, fail.

Stdlib-only.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
CHANGELOG = REPO_ROOT / "CHANGELOG.md"
TAG_RE = re.compile(r"^(v\d+[a-z]+(?:-[a-z]+)?)\s*[:—-]\s*(.+)$")


def run(cmd: list[str], timeout: int = 30) -> tuple[int, str, str]:
    proc = subprocess.run(
        cmd, cwd=str(REPO_ROOT),
        capture_output=True, timeout=timeout, check=False,
    )
    out = (proc.stdout or b"").decode("utf-8", errors="replace")
    err = (proc.stderr or b"").decode("utf-8", errors="replace")
    return proc.returncode, out, err


def collect_commits() -> list[dict]:
    """Each commit entry: {sha, date, tag, headline, body}."""
    rc, out, _ = run([
        "git", "log", "--no-merges",
        "--pretty=format:%H%x1f%cI%x1f%s%x1f%b%x1e",
        "--reverse",
    ], timeout=20)
    if rc != 0:
        return []
    entries: list[dict] = []
    for raw in out.split("\x1e"):
        raw = raw.strip()
        if not raw:
            continue
        parts = raw.split("\x1f")
        if len(parts) < 3:
            continue
        sha, date, subject = parts[0], parts[1], parts[2]
        body = parts[3] if len(parts) > 3 else ""
        m = TAG_RE.match(subject.strip())
        if not m:
            continue
        entries.append({
            "sha": sha[:7],
            "date": date.split("T")[0],
            "tag": m.group(1),
            "headline": m.group(2).strip(),
            "body": body.strip(),
        })
    return entries


def render(entries: list[dict]) -> str:
    if not entries:
        return "# CHANGELOG\n\n*(no v-prefixed commits yet)*\n"

    # Group entries by tag prefix (v78 / v77 / etc.) to produce stable major
    # sections. Within a section, list newest-first.
    by_major: dict[str, list[dict]] = {}
    for e in entries:
        major = re.match(r"v\d+", e["tag"])
        key = major.group(0) if major else e["tag"]
        by_major.setdefault(key, []).append(e)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = [
        "# CHANGELOG",
        "",
        "Auto-generated by `.claude/hooks/gen_changelog.py` from git commits "
        "tagged `v<N><suffix>:` (the AuroraIA-v2 versioning convention).",
        "",
        f"_Last regenerated: {today}_",
        "",
    ]

    for major in sorted(by_major.keys(), reverse=True):
        major_entries = sorted(by_major[major], key=lambda e: e["tag"], reverse=True)
        first_date = min(e["date"] for e in major_entries)
        last_date = max(e["date"] for e in major_entries)
        date_range = first_date if first_date == last_date else f"{first_date} → {last_date}"
        lines.append(f"## {major} — {date_range}")
        lines.append("")
        for e in major_entries:
            lines.append(f"### `{e['tag']}` — {e['headline']}")
            lines.append("")
            lines.append(f"_{e['date']} · `{e['sha']}`_")
            lines.append("")
            if e["body"]:
                # Trim co-author trailers (Anthropic conventions) to keep the
                # changelog tight — the SHA still points to the full message.
                body = e["body"]
                body = re.sub(r"\n+Co-Authored-By:.*", "", body, flags=re.DOTALL).strip()
                if body:
                    # Indent only if there's actual content; one blank line
                    # before/after for readability.
                    lines.append(body)
                    lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Aurora CHANGELOG generator")
    parser.add_argument("--stdout", action="store_true",
                        help="Print to stdout instead of writing CHANGELOG.md")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if CHANGELOG.md is out of sync with git log")
    args = parser.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
    except (AttributeError, ValueError):
        pass

    entries = collect_commits()
    rendered = render(entries)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not CHANGELOG.is_file():
            sys.stderr.write("CHANGELOG.md missing\n")
            return 1
        existing = CHANGELOG.read_text(encoding="utf-8")

        def normalize(text: str) -> str:
            # Tolerate the "Last regenerated" date drifting (otherwise every
            # day produces a spurious diff). Also normalize line endings —
            # Git's autocrlf can store LF while local working copy is CRLF.
            t = re.sub(r"_Last regenerated:.*?_", "_Last regenerated:_", text)
            return t.replace("\r\n", "\n").strip()

        if normalize(existing) == normalize(rendered):
            return 0

        # Tolerate one-commit drift: the regen commit itself cannot include
        # its own entry, so the very latest commit may be missing from the
        # CHANGELOG. Re-render excluding it and compare.
        if entries:
            rendered_minus_last = render(entries[:-1])
            if normalize(existing) == normalize(rendered_minus_last):
                return 0

        sys.stderr.write(
            "CHANGELOG.md is out of sync with git log — re-run "
            "`python .claude/hooks/gen_changelog.py` and commit.\n"
        )
        return 1

    CHANGELOG.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {CHANGELOG} ({len(rendered)} chars, {len(entries)} entries)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
