#!/usr/bin/env python3
"""bridge-doctor — Aurora bridge recovery, cross-platform Python replacement
for update-aurora.bat (which has LF line endings that cmd.exe Windows mangles).

What it does (in order, with safety gates):

1. Verify the working tree is committed + pushed (the user's hard rule:
   "ne JAMAIS lancer update-aurora.bat sans commit+push prealable —
   git reset --hard wipe les modifs"). Refuses to proceed if there are
   uncommitted code changes; lets through .claude/* session artifacts.

2. Find and stop bridge_server.py processes (Win/macOS/Linux).

3. Wait for port 3001 to be released, kill any zombie listeners on it.

4. Optional: git fetch origin main + git reset --hard origin/main
   (only if --pull is passed; default is local-only respawn).

5. Respawn bridge_server.py via subprocess + verify /api/health = 200.

Usage:
    python bridge_doctor.py                # respawn local bridge
    python bridge_doctor.py --pull         # also reset hard to origin/main first
    python bridge_doctor.py --check-only   # diagnose only, don't act
    python bridge_doctor.py --force        # skip the commit+push gate

The script prints concrete progress lines so the user can follow it from
a Bash/PowerShell terminal or from a Claude session. Exits 0 on green
health, non-zero on any failure.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent
APPLICATION_DIR = REPO_ROOT / "application"
BRIDGE_PORT = 3001
HEALTH_URL = f"http://127.0.0.1:{BRIDGE_PORT}/api/health"
SESSION_ARTIFACT_PATHS = (
    ".claude/agent-tracker/state.json",
    ".claude/settings.local.json",
    ".claude/scheduled_tasks.lock",
    ".claude/scheduled_tasks.json",
    ".claude/bridge.out.log",
)
PROBE_TIMEOUT_S = 5.0
RESPAWN_WAIT_S = 8.0


def log(msg: str) -> None:
    # Windows console default codec is cp1252 which crashes on Unicode glyphs
    # like the green check. Reconfigure stdout to UTF-8 (errors='replace' as
    # a final safety net). Idempotent — no-op when already UTF-8.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
    except (AttributeError, ValueError):
        pass
    sys.stdout.write(f"[bridge-doctor] {msg}\n")
    sys.stdout.flush()


def run(cmd: list[str], cwd: Path | None = None, timeout: int = 30) -> tuple[int, str, str]:
    """Run a command. Decode with utf-8 errors='replace' so French Windows
    netstat / locale-specific outputs don't crash on cp1252 bytes."""
    proc = subprocess.run(
        cmd, cwd=str(cwd) if cwd else None,
        capture_output=True, timeout=timeout, check=False,
    )
    out = (proc.stdout or b"").decode("utf-8", errors="replace")
    err = (proc.stderr or b"").decode("utf-8", errors="replace")
    return proc.returncode, out, err


def is_clean_or_only_session_artifacts() -> tuple[bool, list[str]]:
    """Return (clean, dirty_paths). Treat .claude/* session artifacts as
    expendable — they're regenerated by hooks. Anything else dirty blocks."""
    rc, out, _ = run(["git", "-C", str(REPO_ROOT), "status", "--porcelain"])
    if rc != 0:
        return False, ["git status failed"]
    dirty: list[str] = []
    for line in out.splitlines():
        if not line.strip():
            continue
        path = line[3:].strip()
        if path in SESSION_ARTIFACT_PATHS:
            continue
        if path.startswith("?? "):
            # Untracked files don't block (they wouldn't be wiped by reset).
            continue
        dirty.append(path)
    return len(dirty) == 0, dirty


def head_is_pushed() -> bool:
    """True if HEAD is reachable from origin/main."""
    rc, _, _ = run(["git", "-C", str(REPO_ROOT), "fetch", "origin", "main"], timeout=20)
    if rc != 0:
        return False
    rc, out, _ = run(
        ["git", "-C", str(REPO_ROOT), "merge-base", "--is-ancestor", "HEAD", "origin/main"],
    )
    return rc == 0


def find_bridge_pids() -> list[int]:
    """Return PIDs running bridge_server.py."""
    if platform.system() == "Windows":
        rc, out, _ = run([
            "powershell", "-NoProfile", "-Command",
            "Get-CimInstance Win32_Process -Filter \"Name='python.exe'\" "
            "| Where-Object { $_.CommandLine -like '*bridge_server*' } "
            "| Select-Object -ExpandProperty ProcessId",
        ])
        if rc != 0:
            return []
        return [int(p) for p in out.split() if p.strip().isdigit()]
    rc, out, _ = run(["pgrep", "-f", "bridge_server.py"])
    if rc != 0:
        return []
    return [int(p) for p in out.split() if p.strip().isdigit()]


def kill_pid(pid: int) -> bool:
    if platform.system() == "Windows":
        rc, _, _ = run(["taskkill", "/PID", str(pid), "/F"])
    else:
        rc, _, _ = run(["kill", "-9", str(pid)])
    return rc == 0


def port_listeners() -> list[int]:
    """Return PIDs listening on BRIDGE_PORT."""
    if platform.system() == "Windows":
        rc, out, _ = run(["netstat", "-ano"])
        if rc != 0:
            return []
        pids: set[int] = set()
        needle = f":{BRIDGE_PORT} "
        for line in out.splitlines():
            if needle not in line or "LISTENING" not in line:
                continue
            parts = line.split()
            if parts and parts[-1].isdigit():
                pids.add(int(parts[-1]))
        return sorted(pids)
    rc, out, _ = run(["lsof", "-iTCP:" + str(BRIDGE_PORT), "-sTCP:LISTEN", "-t"])
    if rc != 0:
        return []
    return [int(p) for p in out.split() if p.strip().isdigit()]


def port_free() -> bool:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.5)
    try:
        sock.connect(("127.0.0.1", BRIDGE_PORT))
        sock.close()
        return False
    except (ConnectionRefusedError, socket.timeout, OSError):
        return True


def health_ok(timeout: float = PROBE_TIMEOUT_S) -> bool:
    try:
        with urllib.request.urlopen(HEALTH_URL, timeout=timeout) as r:
            data = json.loads(r.read().decode("utf-8"))
            return bool(data.get("ok"))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, OSError):
        return False


def respawn_bridge() -> int:
    """Start a fresh bridge_server.py detached. Return its PID."""
    if not (APPLICATION_DIR / "bridge_server.py").is_file():
        raise FileNotFoundError(f"bridge_server.py missing at {APPLICATION_DIR}")
    if platform.system() == "Windows":
        # CREATE_NEW_CONSOLE=0x00000010, DETACHED_PROCESS=0x00000008
        # Use CREATE_NEW_PROCESS_GROUP so the child survives parent exit.
        flags = 0x00000200  # CREATE_NEW_PROCESS_GROUP
        proc = subprocess.Popen(
            [sys.executable, "bridge_server.py"],
            cwd=str(APPLICATION_DIR), creationflags=flags,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    else:
        proc = subprocess.Popen(
            [sys.executable, "bridge_server.py"],
            cwd=str(APPLICATION_DIR), start_new_session=True,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    return proc.pid


def diagnose() -> dict:
    return {
        "bridge_pids": find_bridge_pids(),
        "port_listeners": port_listeners(),
        "port_free": port_free(),
        "health_ok": health_ok(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Aurora bridge respawn / recovery")
    parser.add_argument("--check-only", action="store_true",
                        help="Diagnose without acting")
    parser.add_argument("--pull", action="store_true",
                        help="git fetch + reset --hard origin/main before respawn")
    parser.add_argument("--force", action="store_true",
                        help="Skip the commit+push gate (dangerous)")
    args = parser.parse_args()

    snap = diagnose()
    log(f"diagnose: {snap}")

    if args.check_only:
        return 0 if snap["health_ok"] else 1

    if not args.force and args.pull:
        clean, dirty = is_clean_or_only_session_artifacts()
        if not clean:
            log(f"REFUSING --pull: dirty paths beyond session artifacts: {dirty}")
            log("commit+push first, or pass --force.")
            return 2
        if not head_is_pushed():
            log("REFUSING --pull: HEAD is not an ancestor of origin/main. Push first.")
            return 2

    bridges = find_bridge_pids()
    if bridges:
        log(f"stopping bridge_server.py PIDs: {bridges}")
        for pid in bridges:
            kill_pid(pid)
        time.sleep(1.5)

    zombies = port_listeners()
    if zombies:
        log(f"port :{BRIDGE_PORT} still held by PIDs {zombies}, killing")
        for pid in zombies:
            kill_pid(pid)
        time.sleep(1.5)

    if args.pull:
        log("git fetch origin main + reset --hard")
        rc, _, err = run(["git", "-C", str(REPO_ROOT), "fetch", "origin", "main"], timeout=30)
        if rc != 0:
            log(f"git fetch failed: {err.strip()[:200]}")
            return 3
        rc, _, err = run(["git", "-C", str(REPO_ROOT), "reset", "--hard", "origin/main"])
        if rc != 0:
            log(f"git reset failed: {err.strip()[:200]}")
            return 3

    deadline = time.time() + 5.0
    while not port_free() and time.time() < deadline:
        time.sleep(0.5)

    pid = respawn_bridge()
    log(f"respawned bridge_server.py PID {pid}, waiting up to {RESPAWN_WAIT_S:.0f}s for /api/health")

    deadline = time.time() + RESPAWN_WAIT_S
    while time.time() < deadline:
        if health_ok():
            log("HEALTH 200 OK")
            return 0
        time.sleep(0.5)
    log("respawn TIMED OUT — bridge did not return /api/health 200")
    return 4


if __name__ == "__main__":
    sys.exit(main())
