/**
 * academicContentVerification — second-pass fact-check for academic items
 * generated by MangaAcademyView (cours, fiches, exos, quiz).
 *
 * Why: the user repeats "pas de fausses fiches", "fiches vraiment bien faite".
 * v50 added grounding sources before generation. This service runs an
 * independent verification pass AFTER generation: it re-reads the produced
 * content against the same sources and returns a verdict + targeted
 * corrections when contradictions are detected.
 *
 * Contract: best-effort, never blocks. If the audit LLM call fails or no
 * sources are available, return a neutral "general" verdict so the content
 * still reaches the user with a transparent badge.
 */

import { ollamaChat } from '../hooks/useTauri.ts'
import type { LearningSource } from './learningResearch.ts'

export type AcademicVerdict = 'verified' | 'general' | 'uncertain' | 'contradicted'

export type AcademicVerificationReport = {
  verdict: AcademicVerdict
  reasoning: string
  citedSources: number[]
  /** When verdict === 'contradicted' the model can return a targeted corrigendum. */
  corrigendum?: string
  /** Optional list of suspect facts that the user should double-check. */
  suspectFacts?: string[]
}

const SYSTEM_PROMPT = `Tu es un correcteur factuel rigoureux. Tu lis un contenu pedagogique et tu juges sa coherence factuelle vis a vis de sources fournies.

Verdicts possibles:
- "verified" : tous les faits notables (dates, formules, auteurs, citations, statistiques) sont coherents avec les sources [Sx].
- "general" : le contenu est plausible mais aucune source ne couvre directement les faits — l ecrit est une connaissance generale acceptable.
- "uncertain" : tu detectes une affirmation douteuse sans pouvoir la trancher (formulation imprecise, fait absent des sources et probablement inexact).
- "contradicted" : une source contredit explicitement un fait du contenu (date fausse, auteur faux, formule fausse, citation faussement attribuee, definition erronee).

Quand verdict = "contradicted", produis un "corrigendum" court (1-3 phrases) qui explique l erreur et donne la bonne version, en citant les sources [Sx] qui prouvent la correction.
Quand tu as releve des affirmations douteuses (verdict "uncertain" ou "verified" partiel), liste-les dans "suspectFacts" (max 5 entrees, formulation tres breve).

Ta sortie est UN UNIQUE objet JSON sous la forme:
{ "verdict": "...", "reasoning": "1-2 phrases", "citedSources": [<int>...], "corrigendum": "...", "suspectFacts": ["..."] }

Regles strictes:
- "citedSources" est la liste des indices [S1, S2, ...] qui couvrent les faits cles du contenu.
- Tu ne reformules PAS le contenu. Tu n inventes PAS de source.
- JSON uniquement, aucun texte avant/apres, aucun bloc markdown.`

function buildSourcesBlock(sources: LearningSource[]): string {
  if (sources.length === 0) return 'Aucune source externe — verifie sur la base de la coherence interne uniquement.'
  return sources
    .map((source, index) => {
      const origin =
        source.origin === 'wikipedia-fr'
          ? 'Wikipedia FR'
          : source.origin === 'wikipedia-en'
            ? 'Wikipedia EN'
            : source.origin === 'duckduckgo'
              ? 'DuckDuckGo'
              : 'Synthese'
      const url = source.url ? ` (${source.url})` : ''
      return `[S${index + 1}] ${origin} — ${source.title}${url}\n  ${source.extract}`
    })
    .join('\n\n')
}

function parseReport(raw: string): AcademicVerificationReport | null {
  const match = raw.match(/\{[\s\S]*\}/)
  if (!match) return null
  try {
    const obj = JSON.parse(match[0]) as Record<string, unknown>
    const verdict = obj.verdict as AcademicVerdict
    if (!['verified', 'general', 'uncertain', 'contradicted'].includes(verdict)) return null
    const citedSources = Array.isArray(obj.citedSources)
      ? (obj.citedSources as unknown[]).map((s) => Number(s)).filter((n) => Number.isFinite(n) && n > 0)
      : []
    const suspectFacts = Array.isArray(obj.suspectFacts)
      ? (obj.suspectFacts as unknown[]).map((s) => String(s).slice(0, 200)).slice(0, 5)
      : undefined
    return {
      verdict,
      reasoning: typeof obj.reasoning === 'string' ? obj.reasoning.slice(0, 400) : '',
      citedSources,
      corrigendum: typeof obj.corrigendum === 'string' ? obj.corrigendum.slice(0, 600) : undefined,
      suspectFacts,
    }
  } catch {
    return null
  }
}

export async function verifyAcademicContent({
  contentTitle,
  contentBody,
  contentKind,
  sources,
  auditModel,
  signal,
}: {
  contentTitle: string
  contentBody: string
  contentKind: 'cours' | 'fiche' | 'exo' | 'quiz'
  sources: LearningSource[]
  auditModel: string
  signal?: AbortSignal
}): Promise<AcademicVerificationReport> {
  if (!contentBody.trim()) {
    return { verdict: 'general', reasoning: 'Contenu vide.', citedSources: [] }
  }

  // Truncate the body so the LLM stays focused on facts and we don't
  // overflow the context window with very long courses.
  const truncated = contentBody.length > 6000
    ? `${contentBody.slice(0, 6000)}\n\n[... contenu tronque pour la verification, fin du contenu ${contentBody.length - 6000} caracteres plus loin ...]`
    : contentBody

  const userMessage = [
    `Type de contenu: ${contentKind}`,
    `Titre: ${contentTitle}`,
    '',
    'Contenu a verifier:',
    truncated,
    '',
    'Sources disponibles:',
    buildSourcesBlock(sources),
    '',
    'Renvoie UNIQUEMENT le JSON {"verdict":"...","reasoning":"...","citedSources":[...],"corrigendum":"...","suspectFacts":[...]}.',
  ].join('\n')

  let raw = ''
  try {
    const response = await ollamaChat(
      auditModel,
      [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userMessage },
      ],
      undefined,
      { signal },
    )
    raw = (response as { message?: { content?: string } })?.message?.content ?? ''
    if (!raw) return fallbackReport()
  } catch {
    return fallbackReport()
  }

  return parseReport(raw) ?? fallbackReport()
}

function fallbackReport(): AcademicVerificationReport {
  return {
    verdict: 'general',
    reasoning: 'Verification automatique indisponible — contenu conserve sans badge.',
    citedSources: [],
  }
}

/**
 * Compose a short HTML/markdown footer the UI can append to a generated
 * cours/fiche to show the verification status visibly.
 *
 * Designed to be readable inside a markdown body: only uses heading + bullets,
 * never raw HTML.
 */
export function reportFooterMarkdown(report: AcademicVerificationReport, sources: LearningSource[]): string {
  const lines: string[] = ['', '---']
  switch (report.verdict) {
    case 'verified':
      lines.push(`> ✓ **Verifie contre ${report.citedSources.length} source(s)** — ${report.reasoning}`)
      break
    case 'general':
      lines.push(`> ◇ **Connaissance generale** — ${report.reasoning}`)
      break
    case 'uncertain':
      lines.push(`> ? **A verifier toi-meme** — ${report.reasoning}`)
      break
    case 'contradicted':
      lines.push(`> ! **Correction appliquee** — ${report.reasoning}`)
      if (report.corrigendum) lines.push(`>`, `> **Corrigendum** : ${report.corrigendum}`)
      break
  }
  if (report.citedSources.length > 0) {
    const cited = report.citedSources
      .map((idx) => sources[idx - 1])
      .filter(Boolean)
      .slice(0, 5)
    if (cited.length > 0) {
      lines.push('', '*Sources verifiees:*')
      for (let i = 0; i < cited.length; i++) {
        const s = cited[i]
        lines.push(`- [S${i + 1}] ${s.title}${s.url ? ` — ${s.url}` : ''}`)
      }
    }
  }
  if (report.suspectFacts && report.suspectFacts.length > 0) {
    lines.push('', '*Faits a re-verifier toi-meme:*')
    for (const f of report.suspectFacts) lines.push(`- ${f}`)
  }
  return lines.join('\n')
}
