// ---------------------------------------------------------------------------
// Brand profile dictionary A
// Extracted from codeIntent.ts during WS1 modularisation.
// ---------------------------------------------------------------------------

import type { BrandDictionaryEntry } from './codeIntentBrandProfiles.ts'

export const BRAND_DICTIONARY_A: BrandDictionaryEntry[] = [
  {
    token: /\bcoca([- ]?cola)?\b/i,
    canonical: 'Coca-Cola',
    domain: 'soda / boisson gazeuse',
    profile: {
      primaryColor: '#F40009',
      secondaryColor: '#FFFFFF',
      productKeywords: ['bouteille en verre', 'canette rouge', 'verre avec glacons', 'logo Spencerian script'],
      designVibe: 'rouge eclatant + blanc, vintage americain pop, bulles, condensation, energie joyeuse',
      typoVibe: 'serif scriptural elegant pour le wordmark + sans bold pour le corps',
      imageQueries: ['Coca-Cola bouteille en verre', 'Coca-Cola canette rouge', 'Coca-Cola logo officiel', 'Coca-Cola ambiance vintage'],
      productShape: 'bottle',
    },
  },
  {
    token: /\bpepsi\b/i,
    canonical: 'Pepsi',
    domain: 'soda',
    profile: {
      primaryColor: '#004B93',
      secondaryColor: '#E32934',
      tertiaryColor: '#FFFFFF',
      productKeywords: ['canette bleue', 'bouteille', 'globe Pepsi'],
      designVibe: 'bleu profond + rouge, moderne, confident, dynamique sport-music',
      typoVibe: 'sans bold geometric',
      imageQueries: ['Pepsi can blue', 'Pepsi bottle modern', 'Pepsi logo globe'],
      productShape: 'can',
    },
  },
  {
    token: /\bfanta\b/i,
    canonical: 'Fanta',
    domain: 'soda',
    profile: {
      primaryColor: '#F58220',
      secondaryColor: '#0066B3',
      productKeywords: ['canette orange', 'bouteille fruit', 'eclats fruits'],
      designVibe: 'orange vif + bleu, fun, jeune, fruite, comic',
      typoVibe: 'sans rounded playful',
      imageQueries: ['Fanta orange can', 'Fanta bottle splash', 'Fanta logo orange'],
      productShape: 'can',
    },
  },
  {
    token: /\bsprite\b/i,
    canonical: 'Sprite',
    domain: 'soda',
    profile: {
      primaryColor: '#009639',
      secondaryColor: '#FFEC00',
      productKeywords: ['canette verte transparente', 'citron vert', 'glacons cristal'],
      designVibe: 'vert frais + jaune citron, frais, transparent, glace',
      typoVibe: 'sans condensed bold',
      imageQueries: ['Sprite green can', 'Sprite logo lemon lime', 'Sprite bottle ice'],
      productShape: 'can',
    },
  },
  {
    token: /\bnutella\b/i,
    canonical: 'Nutella',
    domain: 'pate a tartiner',
    profile: {
      primaryColor: '#3F2A1B',
      secondaryColor: '#E30613',
      productKeywords: ['pot de Nutella', 'tartine pain', 'noisette chocolat'],
      designVibe: 'brun chocolat + rouge logo, gourmand chaleureux, matin familial',
      typoVibe: 'serif italic curve',
      imageQueries: ['Nutella jar', 'Nutella tartine pain', 'Nutella logo officiel'],
      productShape: 'bottle',
    },
  },
  {
    token: /\bstarbucks\b/i,
    canonical: 'Starbucks',
    domain: 'coffee shop',
    profile: {
      primaryColor: '#006241',
      secondaryColor: '#FFFFFF',
      productKeywords: ['gobelet siren', 'cafe latte art', 'mug Starbucks', 'logo siren verte'],
      designVibe: 'vert profond, premium minimal, communautaire, artisanal',
      typoVibe: 'serif tradition + sans soft',
      imageQueries: ['Starbucks cup green', 'Starbucks logo siren', 'Starbucks coffee latte art'],
      productShape: 'cup',
    },
  },
  {
    token: /\bmcdonald'?s?\b/i,
    canonical: "McDonald's",
    domain: 'fast food',
    profile: {
      primaryColor: '#FFC72C',
      secondaryColor: '#DA291C',
      productKeywords: ['Big Mac', 'frites rouges', 'arches dorees', 'happy meal'],
      designVibe: 'jaune doré + rouge feu, convivial, rapide, americain familial',
      typoVibe: 'sans bold rounded',
      imageQueries: ['McDonalds Big Mac', 'McDonalds frites', 'McDonalds golden arches logo'],
      productShape: 'logo',
    },
  },
  {
    token: /\bkfc\b/i,
    canonical: 'KFC',
    domain: 'fast food poulet',
    profile: {
      primaryColor: '#E4002B',
      secondaryColor: '#FFFFFF',
      productKeywords: ['bucket poulet', 'colonel Sanders', 'cuisses croustillantes'],
      designVibe: 'rouge americain + colonel iconic, friture chaleureuse Southern',
      typoVibe: 'serif vintage US',
      imageQueries: ['KFC bucket chicken', 'KFC colonel logo', 'KFC chicken pieces'],
      productShape: 'cup',
    },
  },
  {
    token: /\bburger king\b/i,
    canonical: 'Burger King',
    domain: 'fast food',
    profile: {
      primaryColor: '#D62300',
      secondaryColor: '#F5EBDC',
      tertiaryColor: '#502314',
      productKeywords: ['Whopper', 'flamme grill', 'logo crown burger'],
      designVibe: 'orange brule + creme, flame-grilled rebel cool',
      typoVibe: 'serif chunky retro',
      imageQueries: ['Burger King Whopper', 'Burger King logo', 'Burger King flame grill'],
      productShape: 'logo',
    },
  },
  {
    token: /\btesla\b/i,
    canonical: 'Tesla',
    domain: 'voitures electriques',
    profile: {
      primaryColor: '#E31937',
      secondaryColor: '#000000',
      tertiaryColor: '#F4F4F4',
      productKeywords: ['Model S', 'Model 3', 'Model X', 'Cybertruck', 'Supercharger', 'tableau de bord minimal'],
      designVibe: 'rouge accent sur noir, futur minimaliste, silencieux, premium tech',
      typoVibe: 'sans geometric thin/regular spaced',
      imageQueries: ['Tesla Model S exterior', 'Tesla Model 3 dashboard', 'Tesla Cybertruck', 'Tesla logo silver'],
      productShape: 'car',
    },
  },
  {
    token: /\brenault\b/i,
    canonical: 'Renault',
    domain: 'automobile',
    profile: {
      primaryColor: '#FFCC00',
      secondaryColor: '#000000',
      productKeywords: ['logo losange', 'Megane', 'Clio', 'Captur', 'Twingo'],
      designVibe: 'jaune accent + noir, francais agile, accessible',
      typoVibe: 'sans modern',
      imageQueries: ['Renault logo diamond', 'Renault Megane', 'Renault Clio'],
      productShape: 'car',
    },
  },
  {
    token: /\bpeugeot\b/i,
    canonical: 'Peugeot',
    domain: 'automobile',
    profile: {
      primaryColor: '#0058A3',
      secondaryColor: '#000000',
      productKeywords: ['logo lion', '208', '308', '3008', '5008'],
      designVibe: 'bleu profond + lion, francais elegant, technologique',
      typoVibe: 'serif bold modern',
      imageQueries: ['Peugeot logo lion', 'Peugeot 308', 'Peugeot 3008'],
      productShape: 'car',
    },
  },
  {
    token: /\bbmw\b/i,
    canonical: 'BMW',
    domain: 'automobile premium',
    profile: {
      primaryColor: '#1C69D4',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#000000',
      productKeywords: ['Serie 3', 'M5', 'i7', 'logo helice bleu blanc'],
      designVibe: 'bleu Bavaria sur blanc/noir, premium ingenierie, sportif',
      typoVibe: 'sans corporate clean',
      imageQueries: ['BMW Serie 3 sedan', 'BMW M5 sport', 'BMW logo'],
      productShape: 'car',
    },
  },
  {
    token: /\bporsche\b/i,
    canonical: 'Porsche',
    domain: 'voitures sportives',
    profile: {
      primaryColor: '#D5001C',
      secondaryColor: '#000000',
      tertiaryColor: '#FFFFFF',
      productKeywords: ['911', 'Cayenne', 'Taycan', 'Crest Stuttgart'],
      designVibe: 'rouge sportif sur noir, heritage Stuttgart, performance pure',
      typoVibe: 'serif italic + sans bold',
      imageQueries: ['Porsche 911', 'Porsche Taycan electric', 'Porsche crest logo'],
      productShape: 'car',
    },
  },
  {
    token: /\bapple\b/i,
    canonical: 'Apple',
    domain: 'tech / devices',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#A2AAAD',
      productKeywords: ['iPhone', 'MacBook', 'iPad', 'AirPods', 'Apple Watch', 'logo pomme'],
      designVibe: 'noir / blanc / argent, minimal aere sharp, premium futur sobre',
      typoVibe: 'San Francisco / Helvetica Now sans clean',
      imageQueries: ['Apple iPhone product shot', 'MacBook Pro silver', 'Apple logo silver', 'Apple Park HQ'],
      productShape: 'logo',
    },
  },
  {
    token: /\biphone( ?\d{1,2})?\b/i,
    canonical: 'iPhone',
    domain: 'smartphone Apple',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#A2AAAD',
      tertiaryColor: '#1D1D1F',
      productKeywords: ['iPhone Pro', 'titanium', 'Dynamic Island', 'camera lenses'],
      designVibe: 'noir profond + titane, photo-sharp, tech bijou',
      typoVibe: 'sans display bold + body regular',
      imageQueries: ['iPhone 15 Pro titanium', 'iPhone product shot black', 'iPhone camera detail'],
      productShape: 'phone',
    },
  },
  {
    token: /\bipad\b/i,
    canonical: 'iPad',
    domain: 'tablette Apple',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['iPad Pro', 'Apple Pencil', 'Magic Keyboard', 'M2 chip'],
      designVibe: 'aluminium argent sur fond blanc, productivite creative',
      typoVibe: 'sans clean + accents creatifs',
      imageQueries: ['iPad Pro product', 'Apple Pencil drawing', 'iPad Magic Keyboard'],
      productShape: 'tablet',
    },
  },
  {
    token: /\bairpods\b/i,
    canonical: 'AirPods',
    domain: 'ecouteurs Apple',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#A2AAAD',
      productKeywords: ['AirPods Pro', 'Reduction de bruit active', 'Audio spatial', 'boitier MagSafe', 'Adaptive Audio'],
      designVibe: 'blanc pur produit sur fond clair + noir texte, minimal Apple aere premium',
      typoVibe: 'San Francisco / Helvetica Now sans clean',
      imageQueries: ['AirPods Pro product shot white', 'AirPods Pro case MagSafe', 'AirPods Pro in ear'],
      productShape: 'logo',
    },
  },
  {
    token: /\bapple ?watch\b/i,
    canonical: 'Apple Watch',
    domain: 'montre connectee Apple',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#A2AAAD',
      productKeywords: ['Apple Watch Ultra', 'Series 10', 'cadran', 'bracelet', 'suivi sante'],
      designVibe: 'noir profond + aluminium/titane, tech bijou sportif premium',
      typoVibe: 'San Francisco sans clean',
      imageQueries: ['Apple Watch Ultra product', 'Apple Watch face detail', 'Apple Watch band'],
      productShape: 'logo',
    },
  },
  {
    token: /\bmacbook\b/i,
    canonical: 'MacBook',
    domain: 'laptop Apple',
    profile: {
      primaryColor: '#1D1D1F',
      secondaryColor: '#A2AAAD',
      productKeywords: ['MacBook Pro', 'M3 chip', 'Liquid Retina XDR', 'aluminium unibody'],
      designVibe: 'gris sideral + argent, performance creative, minimal pro',
      typoVibe: 'sans clean tech',
      imageQueries: ['MacBook Pro space gray', 'MacBook M3 chip', 'MacBook keyboard close up'],
      productShape: 'laptop',
    },
  },
  {
    token: /\bsamsung\b/i,
    canonical: 'Samsung',
    domain: 'tech / mobile',
    profile: {
      primaryColor: '#1428A0',
      secondaryColor: '#FFFFFF',
      productKeywords: ['Galaxy S24', 'Galaxy Fold', 'Neo QLED', 'logo bleu'],
      designVibe: 'bleu electrique + blanc, tech innovation grand public',
      typoVibe: 'sans modern',
      imageQueries: ['Samsung Galaxy S24', 'Samsung Galaxy Fold', 'Samsung logo blue'],
      productShape: 'phone',
    },
  },
  {
    token: /\bgoogle\b/i,
    canonical: 'Google',
    domain: 'tech / services',
    profile: {
      primaryColor: '#4285F4',
      secondaryColor: '#EA4335',
      tertiaryColor: '#FBBC04',
      productKeywords: ['logo G colore', 'Pixel', 'Search', 'Material Design'],
      designVibe: 'quadricolore (bleu, rouge, jaune, vert) sur blanc, friendly clean',
      typoVibe: 'Product Sans / Roboto rounded',
      imageQueries: ['Google logo colors', 'Google Pixel phone', 'Google Material Design'],
      productShape: 'logo',
    },
  },
  {
    token: /\bspotify\b/i,
    canonical: 'Spotify',
    domain: 'streaming musical',
    profile: {
      primaryColor: '#1DB954',
      secondaryColor: '#191414',
      productKeywords: ['onde sonore', 'casque audio', 'logo vert', 'playlist cover'],
      designVibe: 'vert neon sur noir, audio musical immersif, vibrant',
      typoVibe: 'Circular bold + sans body',
      imageQueries: ['Spotify logo green', 'Spotify app interface', 'Spotify playlist artwork'],
      productShape: 'logo',
    },
  },
  {
    token: /\bnetflix\b/i,
    canonical: 'Netflix',
    domain: 'streaming video',
    profile: {
      primaryColor: '#E50914',
      secondaryColor: '#000000',
      productKeywords: ['logo N rouge', 'series posters', 'TV cinema'],
      designVibe: 'rouge vif sur noir profond, cinematic dramatique',
      typoVibe: 'sans condensed bold',
      imageQueries: ['Netflix logo red', 'Netflix interface dark', 'Netflix poster grid'],
      productShape: 'logo',
    },
  },
  {
    token: /\byoutube\b/i,
    canonical: 'YouTube',
    domain: 'plateforme video',
    profile: {
      primaryColor: '#FF0000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['bouton play rouge', 'thumbnail video', 'logo rectangle'],
      designVibe: 'rouge play + blanc, video creator friendly',
      typoVibe: 'sans Roboto',
      imageQueries: ['YouTube logo play button', 'YouTube interface', 'YouTube creator'],
      productShape: 'logo',
    },
  },
]
