// ---------------------------------------------------------------------------
// Brand profile dictionary B
// Extracted from codeIntent.ts during WS1 modularisation.
// ---------------------------------------------------------------------------

import type { BrandDictionaryEntry } from './codeIntentBrandProfiles.ts'

export const BRAND_DICTIONARY_B: BrandDictionaryEntry[] = [
  {
    token: /\bnike\b/i,
    canonical: 'Nike',
    domain: 'sportswear',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#FA5400',
      productKeywords: ['Air Max', 'Jordan', 'swoosh', 'sneakers'],
      designVibe: 'noir / blanc + accent orange, swoosh iconic, athletique inspirant',
      typoVibe: 'Futura bold uppercase + sans body',
      imageQueries: ['Nike Air Max sneaker', 'Nike swoosh logo', 'Nike Jordan basketball'],
      productShape: 'shoe',
    },
  },
  {
    token: /\badidas\b/i,
    canonical: 'Adidas',
    domain: 'sportswear',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['Stan Smith', 'Yeezy', 'three stripes', 'Originals'],
      designVibe: 'noir / blanc, three-stripes minimal sportif iconic',
      typoVibe: 'sans condensed bold lowercase',
      imageQueries: ['Adidas Stan Smith', 'Adidas trefoil logo', 'Adidas three stripes'],
      productShape: 'shoe',
    },
  },
  {
    token: /\bpuma\b/i,
    canonical: 'Puma',
    domain: 'sportswear',
    profile: {
      primaryColor: '#1C1C1C',
      secondaryColor: '#FFFFFF',
      productKeywords: ['Suede', 'logo puma jumping', 'sneakers', 'training'],
      designVibe: 'noir + blanc, puma cat dynamique, sport street',
      typoVibe: 'sans bold italic',
      imageQueries: ['Puma Suede sneaker', 'Puma logo cat', 'Puma sport apparel'],
      productShape: 'shoe',
    },
  },
  {
    token: /\bgucci\b/i,
    canonical: 'Gucci',
    domain: 'luxe mode',
    profile: {
      primaryColor: '#0B6623',
      secondaryColor: '#A0001E',
      tertiaryColor: '#F4E1A4',
      productKeywords: ['monogram GG', 'web stripe vert rouge', 'sac luxe', 'mocassin'],
      designVibe: 'vert + rouge sur creme, heritage italien luxe maximaliste',
      typoVibe: 'serif vintage italic',
      imageQueries: ['Gucci monogram bag', 'Gucci logo GG', 'Gucci stripe red green'],
      productShape: 'bag',
    },
  },
  {
    token: /\bprada\b/i,
    canonical: 'Prada',
    domain: 'luxe mode',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['triangle Prada', 'sac', 'mode minimaliste'],
      designVibe: 'noir / blanc minimal, luxe italien architectural',
      typoVibe: 'serif sharp uppercase',
      imageQueries: ['Prada bag triangle logo', 'Prada minimal store', 'Prada fashion show'],
      productShape: 'bag',
    },
  },
  {
    token: /\bairbnb\b/i,
    canonical: 'Airbnb',
    domain: 'location hebergements',
    profile: {
      primaryColor: '#FF5A5F',
      secondaryColor: '#FFFFFF',
      productKeywords: ['logo Belo', 'maison', 'hebergement local'],
      designVibe: 'rose corail + blanc, friendly travel community',
      typoVibe: 'Cereal sans rounded',
      imageQueries: ['Airbnb logo Belo', 'Airbnb home interior', 'Airbnb travel destination'],
      productShape: 'building',
    },
  },
  {
    token: /\buber\b/i,
    canonical: 'Uber',
    domain: 'VTC / livraison',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['voiture VTC', 'app interface', 'logo wordmark'],
      designVibe: 'noir / blanc, technology mobility minimal',
      typoVibe: 'Uber Move sans bold',
      imageQueries: ['Uber logo wordmark', 'Uber app interface', 'Uber driver car'],
      productShape: 'car',
    },
  },
  {
    token: /\bferrari\b/i,
    canonical: 'Ferrari',
    domain: 'voitures sportives premium',
    profile: {
      primaryColor: '#FF2800',
      secondaryColor: '#000000',
      tertiaryColor: '#FFEC00',
      productKeywords: ['cheval cabre', 'F8', 'SF90', 'Monza', 'Maranello'],
      designVibe: 'rouge Rosso Corsa + jaune Modena, exotic supercar Italian heritage',
      typoVibe: 'serif italic sport',
      imageQueries: ['Ferrari F8 red', 'Ferrari prancing horse logo', 'Ferrari SF90'],
      productShape: 'car',
    },
  },
  {
    token: /\blamborghini\b/i,
    canonical: 'Lamborghini',
    domain: 'voitures sportives extremes',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFCC00',
      productKeywords: ['Huracan', 'Aventador', 'Urus', 'taureau dore'],
      designVibe: 'jaune dore + noir, raging bull aggressive futuriste',
      typoVibe: 'sans bold uppercase italic',
      imageQueries: ['Lamborghini Huracan yellow', 'Lamborghini Aventador', 'Lamborghini bull logo'],
      productShape: 'car',
    },
  },
  {
    token: /\bmercedes\b/i,
    canonical: 'Mercedes-Benz',
    domain: 'automobile luxe allemand',
    profile: {
      primaryColor: '#00ADEF',
      secondaryColor: '#000000',
      tertiaryColor: '#C5C5C5',
      productKeywords: ['Classe S', 'AMG GT', 'EQS', 'etoile trois branches'],
      designVibe: 'argent + noir, premium prestige Stuttgart elegance',
      typoVibe: 'serif corporate + sans body',
      imageQueries: ['Mercedes Classe S', 'Mercedes AMG GT', 'Mercedes star logo'],
      productShape: 'car',
    },
  },
  {
    token: /\brolex\b/i,
    canonical: 'Rolex',
    domain: 'horlogerie luxe',
    profile: {
      primaryColor: '#006039',
      secondaryColor: '#FBC600',
      productKeywords: ['Submariner', 'Daytona', 'GMT-Master', 'couronne'],
      designVibe: 'vert profond + or, prestige horlogerie Suisse heritage',
      typoVibe: 'serif corporate elegant',
      imageQueries: ['Rolex Submariner', 'Rolex Daytona gold', 'Rolex crown logo'],
      productShape: 'watch',
    },
  },
  {
    token: /\blouis vuitton\b|\blv\b/i,
    canonical: 'Louis Vuitton',
    domain: 'maroquinerie luxe',
    profile: {
      primaryColor: '#5D3A1A',
      secondaryColor: '#FFD700',
      productKeywords: ['monogram LV', 'sac Speedy', 'Neverfull', 'malle'],
      designVibe: 'brun + or, monogram Parisien heritage maroquinerie',
      typoVibe: 'serif italic Futura mix',
      imageQueries: ['Louis Vuitton monogram bag', 'LV logo gold', 'Louis Vuitton store'],
      productShape: 'bag',
    },
  },
  {
    token: /\bchanel\b/i,
    canonical: 'Chanel',
    domain: 'mode parfum luxe',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#C8A951',
      productKeywords: ['No 5', 'sac 2.55', 'tweed', 'CC interlocking'],
      designVibe: 'noir / blanc + or, Paris haute couture intemporel',
      typoVibe: 'serif italic + sans condensed',
      imageQueries: ['Chanel No 5 perfume', 'Chanel CC logo', 'Chanel 2.55 bag'],
      productShape: 'bottle',
    },
  },
  {
    token: /\bhermes\b|\bhermès\b/i,
    canonical: 'Hermès',
    domain: 'maroquinerie luxe ultra',
    profile: {
      primaryColor: '#FF6E00',
      secondaryColor: '#FFFFFF',
      productKeywords: ['Birkin', 'Kelly', 'carre soie', 'cheval Duc-attele'],
      designVibe: 'orange Hermes + blanc, equestrian Parisian craftsmanship',
      typoVibe: 'serif elegant',
      imageQueries: ['Hermes Birkin bag', 'Hermes orange box', 'Hermes carre silk'],
      productShape: 'bag',
    },
  },
  {
    token: /\bsony\b/i,
    canonical: 'Sony',
    domain: 'electronique audio video',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['casque WH-1000XM5', 'Alpha A7', 'BRAVIA', 'PlayStation'],
      designVibe: 'noir minimal, ingenierie japonaise audio video premium',
      typoVibe: 'sans corporate Helvetica-like',
      imageQueries: ['Sony WH-1000XM5 headphones', 'Sony Alpha camera', 'Sony BRAVIA TV'],
      productShape: 'headphones',
    },
  },
  {
    token: /\bplaystation\b|\bps5\b/i,
    canonical: 'PlayStation',
    domain: 'console gaming Sony',
    profile: {
      primaryColor: '#003791',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#000000',
      productKeywords: ['PS5', 'DualSense', 'logo PS', 'controller'],
      designVibe: 'bleu PS + blanc, gaming next-gen futuriste',
      typoVibe: 'sans display bold',
      imageQueries: ['PlayStation 5 console', 'DualSense controller', 'PlayStation logo'],
      productShape: 'controller',
    },
  },
  {
    token: /\bxbox\b/i,
    canonical: 'Xbox',
    domain: 'console gaming Microsoft',
    profile: {
      primaryColor: '#107C10',
      secondaryColor: '#000000',
      productKeywords: ['Series X', 'controller', 'Halo', 'logo X'],
      designVibe: 'vert Xbox + noir, gaming power Microsoft',
      typoVibe: 'sans bold modern',
      imageQueries: ['Xbox Series X console', 'Xbox controller', 'Xbox green logo'],
      productShape: 'controller',
    },
  },
  {
    token: /\bnintendo\b/i,
    canonical: 'Nintendo',
    domain: 'gaming Nintendo',
    profile: {
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      productKeywords: ['Switch', 'Mario', 'Zelda', 'Joy-Con'],
      designVibe: 'rouge Nintendo + blanc, joyful family gaming Japan',
      typoVibe: 'sans rounded playful',
      imageQueries: ['Nintendo Switch console', 'Nintendo Mario', 'Nintendo logo red'],
      productShape: 'console',
    },
  },
  {
    token: /\bmicrosoft\b/i,
    canonical: 'Microsoft',
    domain: 'tech enterprise',
    profile: {
      primaryColor: '#F25022',
      secondaryColor: '#7FBA00',
      tertiaryColor: '#00A4EF',
      productKeywords: ['Windows', 'Surface', 'Office 365', 'logo 4 carres'],
      designVibe: 'quadricolore (rouge, vert, bleu, jaune), Fluent Design productive',
      typoVibe: 'Segoe UI sans modern',
      imageQueries: ['Microsoft logo 4 squares', 'Microsoft Surface', 'Microsoft Windows 11'],
      productShape: 'logo',
    },
  },
  {
    token: /\bopenai\b/i,
    canonical: 'OpenAI',
    domain: 'AI research',
    profile: {
      primaryColor: '#10A37F',
      secondaryColor: '#000000',
      productKeywords: ['ChatGPT', 'GPT-4', 'logo hexagonal', 'DALL-E'],
      designVibe: 'vert mint + noir, AI cutting-edge minimal scientifique',
      typoVibe: 'sans clean tech',
      imageQueries: ['OpenAI logo', 'ChatGPT interface', 'OpenAI hexagon'],
      productShape: 'logo',
    },
  },
  {
    token: /\banthropic\b|\bclaude\b/i,
    canonical: 'Anthropic',
    domain: 'AI safety research',
    profile: {
      primaryColor: '#D97757',
      secondaryColor: '#191919',
      productKeywords: ['Claude', 'logo A', 'Claude Code'],
      designVibe: 'orange peche + noir, AI thoughtful warm scientifique',
      typoVibe: 'serif modern + sans body',
      imageQueries: ['Anthropic logo', 'Claude AI interface', 'Anthropic orange'],
      productShape: 'logo',
    },
  },
  {
    token: /\bstripe\b/i,
    canonical: 'Stripe',
    domain: 'paiement en ligne',
    profile: {
      primaryColor: '#635BFF',
      secondaryColor: '#0A2540',
      productKeywords: ['logo wordmark', 'paiement card', 'dashboard'],
      designVibe: 'violet electrique + bleu nuit, fintech premium developer-first',
      typoVibe: 'sans Sohne modern',
      imageQueries: ['Stripe logo purple', 'Stripe dashboard', 'Stripe card payment'],
      productShape: 'card',
    },
  },
  {
    token: /\bvercel\b/i,
    canonical: 'Vercel',
    domain: 'hosting frontend',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      productKeywords: ['triangle logo', 'Next.js', 'deploy preview'],
      designVibe: 'noir / blanc minimaliste, Next.js geometric devops',
      typoVibe: 'Inter sans clean',
      imageQueries: ['Vercel logo triangle', 'Vercel dashboard', 'Vercel Next.js'],
      productShape: 'logo',
    },
  },
  {
    token: /\bnotion\b/i,
    canonical: 'Notion',
    domain: 'productivite workspace',
    profile: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      tertiaryColor: '#E16259',
      productKeywords: ['logo N', 'workspace blocks', 'productivity'],
      designVibe: 'noir / blanc minimal warm illustrations friendly',
      typoVibe: 'serif modern + sans body',
      imageQueries: ['Notion logo', 'Notion workspace interface', 'Notion blocks'],
      productShape: 'logo',
    },
  },
  {
    token: /\bikea\b/i,
    canonical: 'IKEA',
    domain: 'mobilier maison',
    profile: {
      primaryColor: '#0058A3',
      secondaryColor: '#FFDA1A',
      productKeywords: ['meuble flatpack', 'BILLY', 'POÄNG', 'logo bleu jaune'],
      designVibe: 'bleu Suede + jaune, mobilier accessible scandinave',
      typoVibe: 'sans Verdana / Noto bold',
      imageQueries: ['IKEA logo blue yellow', 'IKEA furniture catalog', 'IKEA store'],
      productShape: 'building',
    },
  },
  {
    token: /\blego\b/i,
    canonical: 'LEGO',
    domain: 'jouets briques',
    profile: {
      primaryColor: '#D80000',
      secondaryColor: '#FFCD00',
      tertiaryColor: '#000000',
      productKeywords: ['briques colorees', 'minifigure', 'set construction'],
      designVibe: 'rouge + jaune iconique, joyful play creativity bricks',
      typoVibe: 'sans bold rounded',
      imageQueries: ['LEGO bricks colorful', 'LEGO minifigure', 'LEGO logo red yellow'],
      productShape: 'logo',
    },
  },
]
