/**
 * codeOutputFiles — pure parser that extracts a multi-file project
 * structure from a stream of code generated by useCodeViewLogic.
 *
 * The LLM is instructed (codeSystemPrompts) to emit fenced code blocks
 * with filename headers. We tolerate three common shapes:
 *   1. ```ts src/App.tsx
 *      ...code...
 *      ```
 *   2. // File: src/App.tsx
 *      ...code...
 *   3. ### `src/App.tsx` (or just `src/App.tsx` on its own line)
 *      ```
 *      ...code...
 *      ```
 *
 * If no markers found, returns a single virtual file `output.txt` so the
 * file tree never crashes on loose plain-text streams.
 */

export interface ParsedFile {
  path: string
  content: string
  language: string
}

const FENCE_RE = /^```([a-zA-Z0-9+#.-]*)\s*([^\n]*)$/
const FILE_HEADER_RE = /^(?:\/\/|#|<!--)\s*(?:File|Fichier|Path|Filename)\s*[:\-]?\s*([\w./@\-+]+\.\w+)/i
const STANDALONE_PATH_RE = /^(?:###\s+)?[`'"]?([\w./@\-+]+\.\w+)[`'"]?\s*$/
// v82na : the expert system prompt asks the LLM to use the
// `--- FICHIER: path/to.ext ---` separator above each fenced block.
// Match it explicitly so the parser respects the LLM's declared paths
// instead of falling back to content-sniffing.
const EXPERT_HEADER_RE = /^---\s*(?:FICHIER|FILE|PATH)\s*:\s*([^\s][^\n-]*?)\s*---\s*$/i

const EXT_TO_LANG: Record<string, string> = {
  ts: 'typescript', tsx: 'tsx', js: 'javascript', jsx: 'jsx',
  py: 'python', rs: 'rust', go: 'go', java: 'java', kt: 'kotlin',
  swift: 'swift', cpp: 'cpp', c: 'c', cs: 'csharp', rb: 'ruby',
  php: 'php', html: 'markup', htm: 'markup', css: 'css', scss: 'scss',
  json: 'json', yaml: 'yaml', yml: 'yaml', xml: 'markup', sql: 'sql',
  sh: 'bash', bash: 'bash', zsh: 'bash', md: 'markdown',
  toml: 'toml', ini: 'ini', dockerfile: 'docker',
}

function langForPath(path: string, hint?: string): string {
  if (hint && EXT_TO_LANG[hint.toLowerCase()]) return EXT_TO_LANG[hint.toLowerCase()]
  const ext = path.split('.').pop()?.toLowerCase() ?? ''
  return EXT_TO_LANG[ext] ?? 'text'
}

/**
 * v82n7 : content-sniff to pick a sensible filename when the LLM emits a
 * fenced block without a path header. User reported a HTML page being
 * named "block-1.tsx" because the fence said \`\`\`tsx — content sniff
 * overrides the fence hint when content shape is more telling.
 */
function sniffPathFromContent(content: string, fenceLang: string): string {
  const head = content.slice(0, 800)
  // Full HTML document
  if (/<!DOCTYPE\s+html/i.test(head) || /<html[\s>]/i.test(head)) {
    return 'index.html'
  }
  // React/JSX
  if (/import\s+(?:React|.*from\s+['"]react['"])/i.test(head)
      || /export\s+default\s+function\s+\w+\s*\(.*\)\s*\{[\s\S]*return\s*\(?\s*</.test(head)) {
    return 'App.tsx'
  }
  // Vue SFC
  if (/<template\s*>/.test(head) && /<script\s/.test(head)) return 'App.vue'
  // Python script
  if (/^\s*(?:import|from|def|class|if\s+__name__)\b/m.test(head) && fenceLang !== 'tsx') return 'script.py'
  // Shell
  if (/^#!\s*\/(?:usr\/)?bin\/(?:bash|sh|zsh)/.test(head)) return 'script.sh'
  // SQL
  if (/^\s*(?:SELECT|CREATE|INSERT|UPDATE|DELETE|DROP)\s/i.test(head)) return 'query.sql'
  // CSS standalone
  if (/^[\s\n]*[.#a-z][\w-]*\s*\{/i.test(head) && /[:;]\s*[\w-]+/.test(head)
      && !/<html/i.test(head) && !/import /.test(head)) return 'styles.css'
  // JSON
  if (head.trim().startsWith('{') && /["']\w+["']\s*:/.test(head)) return 'data.json'
  // Markdown
  if (/^#{1,3}\s/.test(head) || (head.includes('```') && head.length > 200)) return 'README.md'
  // Fallback to fence hint
  const ext = fenceLang || 'txt'
  return `output.${ext === 'typescript' ? 'ts' : ext}`
}

export function extractGeneratedFiles(stream: string): ParsedFile[] {
  if (!stream || stream.trim().length === 0) return []
  const lines = stream.split('\n')
  const files: ParsedFile[] = []
  let pendingPath: string | null = null
  let inFence = false
  let fenceLang = ''
  let fenceBuffer: string[] = []
  let fenceCurrentPath: string | null = null

  const commitFence = () => {
    if (fenceBuffer.length === 0) return
    const content = fenceBuffer.join('\n')
    // v82n7 : prefer a path the LLM declared, else SNIFF from content
    // (which overrides the fence-language hint — user reported HTML
    // being named .tsx because the fence said tsx).
    const path = fenceCurrentPath ?? pendingPath ?? sniffPathFromContent(content, fenceLang)
    files.push({
      path,
      content,
      language: langForPath(path, fenceLang),
    })
    pendingPath = null
    fenceCurrentPath = null
    fenceBuffer = []
    fenceLang = ''
  }

  // v82ns : robustness — some local LLMs emit a CORRUPTED closing fence.
  // Observed in the wild : "`---" (single backtick + dashes) instead of
  // the proper triple-backtick. The next file's "--- FICHIER: X ---"
  // header is then swallowed inside the still-open fence, and the next
  // ```lang opening fence is mis-interpreted as the closing fence of the
  // previous block, dropping every later file entirely. Defenses :
  //   (a) detect a degenerate closing — a line that is only `---,
  //       `---`, ``--, ```` etc.  in a still-open fence
  //   (b) any new EXPERT_HEADER seen INSIDE a fence force-closes it
  const DEGENERATE_CLOSE_RE = /^[`'"]?-{2,}[`'"]?\s*$|^[`'"]{1,2}\s*-{2,}\s*[`'"]{0,2}\s*$/
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i]
    // EXPERT format takes precedence — `--- FICHIER: path ---`. We now
    // check it whether or not we're in a fence (force-close on hit) so a
    // broken closing fence cannot swallow the next file's header.
    const expertHeader = raw.match(EXPERT_HEADER_RE)
    if (expertHeader) {
      if (inFence) {
        commitFence()
        inFence = false
      }
      pendingPath = expertHeader[1].trim()
      continue
    }
    const fenceMatch = raw.match(FENCE_RE)
    if (fenceMatch) {
      if (inFence) {
        commitFence()
        inFence = false
      } else {
        inFence = true
        fenceLang = fenceMatch[1] ?? ''
        const after = (fenceMatch[2] ?? '').trim()
        if (after && /\.[a-zA-Z0-9]+$/.test(after)) {
          fenceCurrentPath = after.replace(/^[`'"]|[`'"]$/g, '')
        }
      }
      continue
    }
    if (inFence) {
      // Detect degenerate closing fence (`---, ``---, etc.) — observed
      // in real LLM streams. Treat as a fence close, do NOT include in
      // content.
      if (DEGENERATE_CLOSE_RE.test(raw)) {
        commitFence()
        inFence = false
        continue
      }
      fenceBuffer.push(raw)
      continue
    }
    const fileHeader = raw.match(FILE_HEADER_RE)
    if (fileHeader) {
      pendingPath = fileHeader[1]
      continue
    }
    const standalone = raw.match(STANDALONE_PATH_RE)
    if (standalone && /\.[a-zA-Z0-9]+$/.test(standalone[1])) {
      pendingPath = standalone[1]
      continue
    }
  }
  if (inFence) commitFence()

  if (files.length === 0) {
    // No fences at all : sniff the whole stream so the file gets a real
    // name (index.html, script.py, App.tsx) instead of "output.txt".
    const sniffedPath = sniffPathFromContent(stream, '')
    return [{
      path: sniffedPath,
      content: stream.trim(),
      language: langForPath(sniffedPath),
    }]
  }
  return files
}

/**
 * Heuristic: does the generated set look like a runnable web preview?
 * v82n7 : extended to handle THREE shapes via comprehension, no per-site
 * hardcoding :
 *   1. Full HTML document (index.html / contains <html>) → direct iframe
 *   2. Single React/TSX component (export default function App) →
 *      auto-bootstrap via Babel-standalone + ReactDOM CDN, render in
 *      iframe so the user sees the actual component running.
 *   3. Pure CSS demo (single .css file with selectors) → wrap in a
 *      minimal HTML scaffold + inject styles.
 * Returns null when no shape fits (Python, Rust, Go, etc.) — those need
 * the orchestrator full-power dev server, not an iframe.
 */
export function extractWebPreview(files: ParsedFile[]): { html: string; entry: ParsedFile; kind: 'html' | 'react' | 'css' } | null {
  if (files.length === 0) return null
  // Shape 1 : full HTML document
  const indexHtml = files.find((f) =>
    f.path.toLowerCase().endsWith('index.html')
    || f.path.toLowerCase() === 'index.html',
  )
  const htmlEntry = indexHtml ?? files.find((f) => /<html[\s>]/i.test(f.content))
  if (htmlEntry) {
    let html = htmlEntry.content
    // v85f : a srcDoc iframe has NO base URL, so any local <link href="style.css">
    // or <script src="script.js"> 404s → console errors + an unstyled/BLACK page.
    // Strip LOCAL stylesheet links and script srcs (keep CDN/absolute), then
    // inline the project's real CSS/JS so the preview actually renders.
    html = html.replace(/<link\b[^>]*\brel=["']?stylesheet["']?[^>]*>/gi,
      (tag) => (/\bhref=["']https?:\/\//i.test(tag) || /\bhref=["']\/\//i.test(tag)) ? tag : '')
    html = html.replace(/<script\b[^>]*\bsrc=["'][^"']+["'][^>]*>\s*<\/script>/gi,
      (tag) => (/\bsrc=["']https?:\/\//i.test(tag) || /\bsrc=["']\/\//i.test(tag)) ? tag : '')

    const cssFiles = files.filter((f) => f !== htmlEntry && /\.(css|scss|less)$/i.test(f.path))
    const jsFiles = files.filter((f) => f !== htmlEntry
      && /\.(m?js|jsx)$/i.test(f.path) && f.language !== 'json')

    if (cssFiles.length > 0) {
      const styleTag = `<style data-aurora-inline>\n${cssFiles.map((f) => `/* ${f.path} */\n${f.content}`).join('\n\n')}\n</style>`
      html = /<\/head>/i.test(html) ? html.replace(/<\/head>/i, `${styleTag}\n</head>`) : `${styleTag}\n${html}`
    }
    if (jsFiles.length > 0) {
      const scriptTag = `<script data-aurora-inline>\n${jsFiles.map((f) => `/* ${f.path} */\n${f.content}`).join('\n;\n')}\n</script>`
      html = /<\/body>/i.test(html) ? html.replace(/<\/body>/i, `${scriptTag}\n</body>`) : `${html}\n${scriptTag}`
    }
    return { html, entry: htmlEntry, kind: 'html' }
  }
  // Shape 2 : React/TSX entry component. Detect by either filename
  // (App.tsx/App.jsx) OR content shape (export default function with
  // JSX return).
  const reactEntry = files.find((f) => {
    if (!/\.(tsx?|jsx?)$/i.test(f.path)) return false
    const c = f.content
    return /export\s+default\s+(?:function\s+\w+|\w+)/.test(c)
      && /return\s*\(?\s*</.test(c)
  })
  if (reactEntry) {
    // Bundle every other CSS sibling into <style>, every other TSX into
    // separate Babel scripts. The entry must mount itself OR provide a
    // default export — we mount it via a small launcher.
    const cssBlocks: string[] = []
    const otherTsxBlocks: string[] = []
    for (const f of files) {
      if (f === reactEntry) continue
      if (f.language === 'css') {
        cssBlocks.push(`/* ${f.path} */\n${f.content}`)
      } else if (/\.(tsx?|jsx?)$/i.test(f.path)) {
        otherTsxBlocks.push(`// ${f.path}\n${f.content}`)
      }
    }
    const componentName = (reactEntry.content.match(/export\s+default\s+function\s+(\w+)/)?.[1])
      ?? (reactEntry.content.match(/export\s+default\s+(\w+)/)?.[1])
      ?? 'App'
    // Strip "export default" keywords so Babel-standalone doesn't choke
    // (no module system in <script type="text/babel">).
    const stripExports = (src: string) => src
      .replace(/export\s+default\s+/g, '')
      .replace(/export\s+\{[^}]*\}\s*;?/g, '')
      .replace(/^\s*import\s+.*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    const html = `<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>aurora-react-preview</title>
<style>html,body,#root{margin:0;padding:0;width:100%;height:100%;font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#0c0a09;color:#f5f5f5}</style>
${cssBlocks.length > 0 ? `<style data-aurora-bundled="css">${cssBlocks.join('\n\n')}</style>` : ''}
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
<script src="https://unpkg.com/@babel/standalone@7/babel.min.js"></script>
</head>
<body>
<div id="root"></div>
<script type="text/babel" data-presets="env,react,typescript" data-type="module">
${otherTsxBlocks.map(stripExports).join('\n\n')}
${stripExports(reactEntry.content)}
const __aurora_root = ReactDOM.createRoot(document.getElementById('root'));
__aurora_root.render(React.createElement(${componentName}));
</script>
</body>
</html>`
    return { html, entry: reactEntry, kind: 'react' }
  }
  // Shape 3 : pure CSS demo (single .css file with rules)
  const cssOnly = files.length === 1 && files[0].language === 'css'
  if (cssOnly) {
    const css = files[0]
    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>aurora-css-preview</title>
<style>${css.content}</style>
</head>
<body><div class="preview-stage">
<h1>Heading 1</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<button>Bouton</button>
<a href="#">Lien</a>
<input placeholder="Champ" />
<ul><li>Item 1</li><li>Item 2</li></ul>
</div></body></html>`
    return { html, entry: css, kind: 'css' }
  }
  return null
}
