/**
 * Subject-specific design hints. The generic PREMIUM_HTML_REFERENCE covers
 * the universal patterns (mesh gradient hero, glassmorphism nav, scroll
 * reveal). These additional blocks tune the structure to the actual subject
 * the user is asking for — saas needs pricing tiers, ecommerce needs product
 * cards with cart, portfolio needs project gallery, dashboard needs sidebar.
 */
export type SubjectVariant = 'saas' | 'portfolio' | 'ecommerce' | 'dashboard' | 'landing' | '3d_scene' | 'game' | 'mobile' | 'desktop' | 'brand_landing' | null

export const SUBJECT_VARIANTS: Record<Exclude<SubjectVariant, null>, string[]> = {
  saas: [
    '### SECTIONS SPECIFIQUES SAAS (ajoute en plus de la structure de base)',
    '- Hero: focus value-prop B2B + 1 ligne courte explicite + capture d ecran/dashboard preview a droite (canvas/SVG anime).',
    '- Section "Logos clients" en marquee horizontal (animation translateX infinie 30s ease-linear).',
    '- "Features grid" 6-9 cards avec icone SVG + titre court + 2-3 lignes (pas de paragraphes).',
    '- "Comment ca marche" 3 etapes numerotees avec stepper visuel (cercles connectes par lignes).',
    '- "Pricing tiers": 3 plans (free/pro/enterprise) en cartes avec liste features + CTA. Le plan recommande a un border accent + label "Le plus populaire".',
    '- "Integrations": grille de 12-20 logos (SVG inline ou tile colore) qui s anime au hover.',
    '- "Testimonials" avec photo (svg avatar) + nom + role + 2 lignes.',
    '- "FAQ" accordion avec animation hauteur (max-height transition 350ms).',
    '- CTA final FORT: bouton XL gradient + microcopy rassurant ("essai gratuit, sans CB requise").',
  ],
  portfolio: [
    '### SECTIONS SPECIFIQUES PORTFOLIO (ajoute en plus de la structure de base)',
    '- Hero personnel: nom + role + 1 ligne mission, photo/illustration ronde a droite.',
    '- "Selected work" gallery masonry (grid-template-columns:repeat(auto-fill, minmax(280px, 1fr)) + grid-auto-rows:minmax(200px, auto)).',
    '- Chaque project card: image preview + titre + tags + hover overlay avec description + lien.',
    '- Animation gallery: stagger fade-in (delay incremental 80ms par card via JS ou CSS animation-delay).',
    '- "Case study" detail: cover image, contexte 1 paragraphe, role+stack en bullets, screenshots avec scroll horizontal sur mobile.',
    '- "About me" colonne gauche photo, droite bio + skills tags (pills).',
    '- "Contact" form simple (3 fields) + email direct + reseaux (icons SVG inline).',
    '- Cursor custom (optional) ou cursor blob qui suit la souris (mousemove + translate3d throttled rAF).',
    '- Footer minimal avec annee dynamique.',
  ],
  ecommerce: [
    '### SECTIONS SPECIFIQUES ECOMMERCE (ajoute en plus de la structure de base)',
    '- Hero: best-seller en vedette + CTA "Decouvrir" + visuel produit central (image ou SVG stylise).',
    '- "Categories" grid 4-6 cards avec image + label, hover scale 1.04 + shadow accru.',
    '- "Products grid" 12-24 cards: image, badge promo si applicable, titre, prix barre + prix actuel, etoiles rating (svg), bouton "Ajouter au panier".',
    '- Quick view au hover: overlay translucent avec bouton "Voir details" (smooth scale-up).',
    '- "Filters sidebar" (desktop) ou drawer (mobile): categories, prix range, marques, taille, couleur (chips).',
    '- "Cart drawer" sticky right: items list, qty +/-, total, bouton "Commander". Anime avec slide-in 300ms.',
    '- "Reviews" carousel scroll horizontal scroll-snap-type:x mandatory.',
    '- Footer 4 cols: shop, aide, marque, newsletter form.',
    '- Trust badges: livraison gratuite, retour 30j, paiement secure, SAV.',
  ],
  dashboard: [
    '### SECTIONS SPECIFIQUES DASHBOARD (ajoute en plus de la structure de base)',
    '- Layout: sidebar fixe gauche (240px) + main contenu. Sidebar avec logo top, nav items (icone + label), user pill bottom.',
    '- Top bar dans le main: titre page courante, search bar centrale, notifications (icon + badge), theme toggle, avatar user.',
    '- "KPI cards" row: 4 cartes avec gros chiffre + delta % (vert/rouge avec fleche), sparkline mini SVG en bas.',
    '- "Main chart" panel: line/bar chart en CSS pur ou via canvas (axes + legend + tooltip on hover).',
    '- "Data table" avec header sticky, rows zebrees subtilement, hover row, sort icons, pagination.',
    '- "Activity feed" colonne droite: liste evenements recents avec icones colorees + timestamp.',
    '- "Quick actions" cards 2x2 avec icone gradient + label.',
    '- Skeleton loaders pendant le data fetch (CSS animation gradient sweep).',
    '- Tous les chiffres animes au mount via counter easeOutCubic 1200ms.',
    '- Mobile: sidebar devient drawer toggleable, KPI cards stackees, table scrollable horizontal.',
  ],
  landing: [
    '### SECTIONS SPECIFIQUES LANDING (ajoute en plus de la structure de base)',
    '- Hero focus: value-prop forte + 2 CTAs + visuel mockup/illustration impactant.',
    '- "Social proof": logos partners + chiffres cles (1M users, 4.8 rating).',
    '- "Features highlights" 3 colonnes avec icones colorees + 2 lignes chacune.',
    '- "How it works" 3 etapes numerotees illustrees.',
    '- "Pricing" simple (1-3 tiers) ou single CTA si gratuit.',
    '- "FAQ" accordion 5-8 questions.',
    '- Final CTA full-width section.',
  ],
  '3d_scene': [
    '### SECTIONS SPECIFIQUES SCENE 3D INTERACTIVE',
    '- IMPORTS THREE.JS via CDN ESM jsdelivr 0.160 — `import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js"`.',
    '- OrbitControls + GLTFLoader + RGBELoader + RoomEnvironment + EffectComposer + UnrealBloomPass + OutputPass via examples/jsm/.',
    '- Si physique implicite: Rapier3D-compat — `import RAPIER from "https://cdn.jsdelivr.net/npm/@dimforge/rapier3d-compat@0.13.0/+esm"` puis `await RAPIER.init()`.',
    '- WebGLRenderer: `antialias:true, alpha:true, powerPreference:"high-performance"`, `setPixelRatio(min(devicePixelRatio, 2))`, `outputColorSpace = SRGBColorSpace`, `toneMapping = ACESFilmicToneMapping`, `toneMappingExposure ≈ 1.1`, `shadowMap.enabled = true`, `shadowMap.type = PCFSoftShadowMap`.',
    '- Camera: PerspectiveCamera(45-55 fov, aspect, 0.1, 200), position cinematique (3/4 angle).',
    '- ECLAIRAGE PREMIUM: HemisphereLight(skyBlue→groundOrange, 0.4-0.6) + DirectionalLight cle (1.5-2.5, castShadow, mapSize 2048, bias -0.0001) + PointLight/SpotLight accent coloree.',
    '- COULEURS LUMIERES stylees: pas du blanc plat — palette violet/orange / teal/magenta / gold/blue selon mood.',
    '- MATERIALS PBR uniquement: MeshStandardMaterial / MeshPhysicalMaterial (NEVER MeshBasic sauf billboards). Config roughness, metalness, clearcoat, transmission, ior, iridescence, sheen.',
    '- ENVIRONMENT: RoomEnvironment (built-in, offline) attache a `scene.environment` ET `scene.background = environment` ou un fond travaille (color sombre + fog).',
    '- POST-PROCESSING: RenderPass + UnrealBloomPass(threshold:0.85, strength:0.5-0.9, radius:0.6) + OutputPass. composer.render() au lieu de renderer.render().',
    '- COMPOSITION: minimum 5-15 objets distincts dans la scene, JAMAIS un seul mesh isole. Foreground/mid/background, regle des tiers.',
    '- ANIMATION: requestAnimationFrame avec DELTA TIME (clock.getDelta()), variations rotation/sin-flottement/pulse/bobbing.',
    '- INTERACTION: OrbitControls(enableDamping:true, dampingFactor:0.06, autoRotate:true jusqu au premier clic) + Raycaster sur pointermove pour highlight emissive.',
    '- Sol PBR (plane 100x100, MeshPhysicalMaterial clearcoat:0.1, roughness:0.4) + ombres recues + brouillard scene.fog atmospherique.',
    '- INSTANCED MESH si >100 objets repetitifs (foret, swarm, particules).',
    '- Shader GLSL custom (au moins UN): hologramme fresnel, glow rim, mesh gradient procedural, ou water sin+noise displacement.',
  ],
  game: [
    '### SECTIONS SPECIFIQUES JEU WEB (canvas 2D ou Three.js 3D)',
    '- Boucle de jeu: requestAnimationFrame avec delta time (`const delta = (now - lastTime) / 1000`) — JAMAIS setInterval.',
    '- Gestion clavier complete: keydown + keyup pour directions, prevention scroll par espace/fleches (e.preventDefault).',
    '- Gestion tactile (touchstart/touchend) si le jeu est jouable au tap.',
    '- localStorage pour les meilleurs scores (high score persistent).',
    '- Web Audio API: AudioContext cree au premier geste utilisateur (autoplay policy), 3+ sons synthetises (action, score, game over) via OscillatorNode + GainNode.',
    '- ECRANS COMPLETS obligatoires: demarrage stylise + jeu + pause (touche P/Escape) + game over avec score + meilleur score + bouton "Rejouer".',
    '- Progression: difficulte croissante (vitesse, ennemis, patterns).',
    '- "Juice" obligatoire: particles, screen shake (CSS transform translate), flash blanc 100ms, trainees, feedback immediat sur chaque action.',
    '- Responsive: canvas s adapte a la fenetre via resize listener (canvas.width/height = innerWidth/Height).',
    '- visibilitychange → pause auto quand l onglet perd le focus.',
    '- Cleanup: removeEventListener au destroy pour eviter les fuites au reload.',
  ],
  mobile: [
    '### SECTIONS SPECIFIQUES APP MOBILE (React Native ou Flutter)',
    '- React Native: `npx create-expo-app` avec Expo Router pour navigation file-based.',
    '- Flutter: `flutter create` avec Material 3 + Material You theming.',
    '- ATOMS premium: cards avec elevation/shadow + radius, buttons avec ripple/haptic feedback, inputs avec floating label.',
    '- LAYOUT respecte safe-area-insets (notch, home indicator) via SafeAreaView (RN) ou SafeArea (Flutter).',
    '- ANIMATIONS: react-native-reanimated v3 (RN) ou implicit/explicit animations (Flutter) pour transitions naturelles.',
    '- DARK MODE auto via prefers-color-scheme equivalent (Appearance API RN, MediaQuery Flutter).',
    '- TYPO premium: SF Pro/Roboto/Inter via expo-font ou GoogleFonts package.',
    '- ICONOGRAPHIE: lucide-react-native (RN) ou material-symbols (Flutter), 24px standard.',
    '- BOTTOM NAV ou tabs avec icones + labels, avec indicator anime au tab actif.',
    '- ECRANS: home, detail, search, settings, profile minimum.',
    '- Pull-to-refresh + infinite scroll quand pertinent.',
    '- Skeleton loaders pendant les fetchs (shimmer).',
  ],
  desktop: [
    '### SECTIONS SPECIFIQUES APP DESKTOP (Tauri ou Electron)',
    '- Tauri: shell Rust + frontend Vite/React, Cargo.toml + tauri.conf.json + src-tauri/.',
    '- Electron: main.js + preload.js + renderer.js, contextIsolation:true.',
    '- Window decoration: titleBarStyle:"hiddenInset" (mac) ou customisee (Win/Linux) pour look pro.',
    '- TRAFFIC LIGHTS macOS conserves, frame customise sur Win/Linux avec close/min/max boutons.',
    '- LAYOUT: sidebar gauche + main, comme une app desktop pro (Notion, Linear, VS Code).',
    '- COMMAND PALETTE Cmd+K avec fuzzy search (kbar, cmdk, ou implementation maison).',
    '- KEYBOARD SHORTCUTS visibles dans une cheatsheet (?). Tous les actions principales accessibles au clavier.',
    '- AUTO-UPDATER (Tauri updater plugin / electron-updater) configure.',
    '- TRAY ICON systeme avec menu contextuel.',
    '- SETTINGS persistantes (Tauri Store / electron-store).',
    '- Dark mode + theme switcher visible dans settings.',
    '- Fenetre min size raisonnable (800x600), launcher launches avec dimensions sauvegardees.',
  ],
  brand_landing: [
    '### SECTIONS SPECIFIQUES BRAND LANDING (page produit / marque iconique)',
    '',
    '⚠️ CHECKLIST OBLIGATOIRE A VERIFIER AVANT D ECRIRE LE PREMIER CARACTERE DE CODE:',
    '  [ ] Three.js scene avec produit 3D procedural (recipe productShape definie en amont).',
    '  [ ] ShaderMaterial Hologramme Fresnel sur halo entourant le produit (code copy-paste fourni plus bas — DOIT etre present sinon la sortie est REJETEE par la gate de fidelite).',
    '  [ ] EffectComposer + UnrealBloomPass (composer.render() au lieu de renderer.render()).',
    '  [ ] OrbitControls(autoRotate:true).',
    '  [ ] >= 2 markers PLACEHOLDER_SUBJECT_IMG_* dans la page.',
    '  [ ] Couleur primaire de la marque dominante 50-70% du visuel.',
    '  [ ] Nom de la marque dans <title>, <h1> du hero, et 3+ sections.',
    'Tu coches mentalement chacun avant de generer. Si un seul est manque, repense la structure AVANT le code.',
    '',
    '- LECTURE DU SUJET: cette page parle d UNE marque ou d UN produit precis (ex: Coca-Cola, Tesla, iPhone). La marque est citee dans le bloc VERROUILLAGE SUJET en amont.',
    '- HERO IMMERSIF: occupe au moins 100vh.',
    '  - Background: gradient vertical/diagonal aux COULEURS DE LA MARQUE (primaire vers noir, ou primaire vers secondaire). PAS le mesh-gradient violet/cyan/ambre du starter generique.',
    '  - Headline en clamp(3rem, 7vw, 6.5rem), font-weight 800-900, kerning serre (-0.03em). Gradient text optionnel mais subtil.',
    '  - Subheadline 1-2 lignes (max 18 mots) tournee marque/produit (ex: "Le rouge le plus celebre du monde, depuis 1886").',
    '  - 2 CTAs (primaire pleine + ghost/outline), accent primaire de la marque.',
    '  - Visuel principal a droite OU centre: <img src="PLACEHOLDER_SUBJECT_IMG" ...> (image reelle du produit/logo) + glow halo derriere via box-shadow ou ::after blur.',
    '  - Particle / bulle / etoile / flamme system en canvas absolute pointer-events:none, theme-coherent (bulles blanches pour soda, etoiles pour Apple, flammes pour Burger King, etc.).',
    '- SECTION HERITAGE / STORYTELLING: bandeau rapide avec date/origine + 1-2 lignes mythologiques de la marque, image lifestyle PLACEHOLDER_SUBJECT_IMG_2 en arriere-plan parallax.',
    '- SECTION PRODUITS / VARIANTES: grille 3-6 cards (chaque card = un produit ou une variante). Chaque card avec PLACEHOLDER_SUBJECT_IMG_* OU SVG inline marque-coherent. Hover = scale(1.04) + tilt 3D leger (transform: perspective(1000px) rotateY(...)) selon mouseX.',
    '- SECTION 3D / EFFET SIGNATURE: au moins UN bloc visuel ambitieux:',
    '  - Three.js via CDN ESM (https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js) — produit en rotation OrbitControls auto-rotate, MeshPhysicalMaterial PBR aux couleurs marque, environment + bloom.',
    '  - OU CSS 3D pur: produit (canette, bottle, phone) construit en plusieurs <div> avec transform translateZ + rotateY animation infinite.',
    '  - OU canvas particle system signature (bulles montant, vapeur, etoiles, fumee de pneu) plein ecran derriere la section.',
    '- SECTION GALLERY / SHOWCASE: parallax stack ou marquee horizontale d images reelles de la marque (PLACEHOLDER_SUBJECT_IMG_1...3 + reuse).',
    '- SECTION CHIFFRES / IMPACT: 3-4 KPI gigantesques anime au scroll (counter easeOutCubic 1500ms): "1.9 milliard de canettes/jour", "200 pays", etc. — adapte les chiffres au contexte de la marque.',
    '- SECTION CITATION ICONIQUE: une grosse citation a propos de la marque (jingle, slogan, phrase fondateur), typo serif/script imposante, contraste fort.',
    '- CTA FINAL pleine largeur: bandeau couleur primaire de la marque + headline puissante + bouton XL.',
    '- FOOTER 4 cols: marque (mini-logo SVG inline), liens, reseaux, newsletter.',
    '',
    '### EXIGENCES VISUELLES SPECIFIQUES BRAND',
    '- TYPO HERITAGE: si la marque a un wordmark celebre (Coca Spencerian, Disney, Ford italic), evoque-le via Google Fonts ("Pacifico", "Lobster", "Playfair Display Italic", "Bungee"). PAS Inter generique partout.',
    '- COULEURS PURES: la couleur primaire doit dominer 50-70% du visuel, secondaire 20-30%, neutres 10-20%. PAS de violet/rose generique du starter.',
    '- TEXTURES: noise overlay + leger grain + condensation/reflets selon contexte (ex: gouttelettes pour soda).',
    '- ANIMATIONS DECLENCHEES PAR SCROLL: chaque section reveal stagger, hero parallax sur scrollY, blob particle qui suit la souris.',
    '- AUCUNE STOCK PHOTO GENERIQUE: utilise les PLACEHOLDER_SUBJECT_IMG_* (images reelles de la marque). Si tu veux du complementaire, fais des SVG inline marque-coherent (logo simplifie, pictogrammes thematiques).',
    '',
    '### EFFET SHADER GLSL SIGNATURE — OBLIGATOIRE (NON-OPTIONNEL, COPIE LE BLOC CI-DESSOUS)',
    'CHAQUE page brand_landing DOIT inclure le shader Hologramme Fresnel ci-dessous. Pas de "tu peux choisir parmi A/B/C", c est le shader DEFAUT a integrer SAUF si tu prefere une autre option dans la liste qui suit. Copie ce code dans ton <script type="module"> apres avoir cree la scene principale, AVANT le rendu.',
    '',
    '```js',
    '// ===== SHADER HOLOGRAMME FRESNEL — copy-paste, change PRIMARY_COLOR_HEX =====',
    'const haloMat = new THREE.ShaderMaterial({',
    '  uniforms: {',
    '    uColor: { value: new THREE.Color("PRIMARY_COLOR_HEX") },  // <-- ex: "#F40009" pour Coca',
    '    uTime: { value: 0 },',
    '  },',
    '  vertexShader: `',
    '    varying vec3 vNormalW;',
    '    varying vec3 vViewDir;',
    '    void main() {',
    '      vec4 worldPos = modelMatrix * vec4(position, 1.0);',
    '      vNormalW = normalize(mat3(modelMatrix) * normal);',
    '      vViewDir = normalize(cameraPosition - worldPos.xyz);',
    '      gl_Position = projectionMatrix * viewMatrix * worldPos;',
    '    }',
    '  `,',
    '  fragmentShader: `',
    '    uniform vec3 uColor;',
    '    uniform float uTime;',
    '    varying vec3 vNormalW;',
    '    varying vec3 vViewDir;',
    '    void main() {',
    '      float fresnel = pow(1.0 - max(dot(vNormalW, vViewDir), 0.0), 3.0);',
    '      float pulse = 0.7 + 0.3 * sin(uTime * 2.0);',
    '      gl_FragColor = vec4(uColor * fresnel * 1.4 * pulse, fresnel);',
    '    }',
    '  `,',
    '  transparent: true,',
    '  blending: THREE.AdditiveBlending,',
    '  depthWrite: false,',
    '})',
    '// Halo mesh = clone du produit principal scaled-up 1.08x avec haloMat',
    'const halo = new THREE.Mesh(productMesh.geometry, haloMat)',
    'halo.scale.setScalar(1.08)',
    'productMesh.add(halo)',
    '// Animation update (dans le requestAnimationFrame loop):',
    '// haloMat.uniforms.uTime.value = clock.getElapsedTime()',
    '```',
    '',
    'CE BLOC EST OBLIGATOIRE. Si tu ne l inclus pas, le rendu sera rejete par la gate de fidelite.',
    '',
    '### ALTERNATIVES (si une option B/C/D/E te semble plus adaptee, tu peux la SUBSTITUER au shader Fresnel mais TOUJOURS mettre UN shader)',
    '',
    'Option A — Hologramme Fresnel sur le produit 3D (recommande pour can/bottle/phone/watch/headphones):',
    '```js',
    'const fresnelMat = new THREE.ShaderMaterial({',
    '  uniforms: {',
    '    uColor: { value: new THREE.Color("PRIMARY_COLOR_HEX") },',
    '    uTime: { value: 0 },',
    '    uIntensity: { value: 1.4 },',
    '  },',
    '  vertexShader: `',
    '    varying vec3 vWorldNormal;',
    '    varying vec3 vViewDir;',
    '    void main() {',
    '      vec4 worldPos = modelMatrix * vec4(position, 1.0);',
    '      vWorldNormal = normalize(mat3(modelMatrix) * normal);',
    '      vViewDir = normalize(cameraPosition - worldPos.xyz);',
    '      gl_Position = projectionMatrix * viewMatrix * worldPos;',
    '    }`,',
    '  fragmentShader: `',
    '    uniform vec3 uColor; uniform float uTime; uniform float uIntensity;',
    '    varying vec3 vWorldNormal; varying vec3 vViewDir;',
    '    void main() {',
    '      float fresnel = pow(1.0 - max(dot(vWorldNormal, vViewDir), 0.0), 3.0);',
    '      float pulse = 0.7 + 0.3 * sin(uTime * 2.0);',
    '      vec3 col = uColor * fresnel * uIntensity * pulse;',
    '      gl_FragColor = vec4(col, fresnel);',
    '    }`,',
    '  transparent: true, blending: THREE.AdditiveBlending, depthWrite: false,',
    '})',
    '// puis chaque frame: fresnelMat.uniforms.uTime.value = clock.getElapsedTime()',
    '// applique-le sur un mesh halo legerement scale-up autour du produit principal.',
    '```',
    '',
    'Option B — Iridescence physique (recommande pour bag/shoe/cup/card):',
    '- MeshPhysicalMaterial avec iridescence: 1.0, iridescenceIOR: 1.5, iridescenceThicknessRange: [100, 800]',
    '- Reflets arc-en-ciel automatiques physiquement corrects, plus realistes que le shader fresnel.',
    '- Combine avec metalness:0.3, roughness:0.4 pour un soft sheen luxueux.',
    '',
    'Option C — Liquid mesh gradient background (recommande pour logo):',
    '```js',
    'const bgMat = new THREE.ShaderMaterial({',
    '  uniforms: { uTime: { value: 0 }, uColor1: { value: new THREE.Color("PRIMARY_COLOR_HEX") }, uColor2: { value: new THREE.Color("SECONDARY_COLOR_HEX") } },',
    '  vertexShader: `varying vec2 vUv; void main() { vUv = uv; gl_Position = vec4(position, 1.0); }`,',
    '  fragmentShader: `',
    '    uniform float uTime; uniform vec3 uColor1; uniform vec3 uColor2; varying vec2 vUv;',
    '    float fbm(vec2 p) { float v = 0.0; float a = 0.5;',
    '      for (int i = 0; i < 5; i++) { v += a * sin(p.x * 1.3 + p.y * 2.1 + uTime * 0.4); p *= 2.0; a *= 0.5; }',
    '      return v;',
    '    }',
    '    void main() {',
    '      float n = fbm(vUv * 3.0);',
    '      vec3 col = mix(uColor1, uColor2, smoothstep(-0.3, 0.7, n));',
    '      gl_FragColor = vec4(col, 1.0);',
    '    }`,',
    '})',
    '// applique sur PlaneGeometry plein-ecran derriere la scene (z=-10).',
    '```',
    '',
    'Option D — Particle attractor au curseur (recommande pour controller/console/headphones):',
    '- BufferGeometry avec 5000 points, attribut position random sphere',
    '- ShaderMaterial vertex shader morph position vers uniforms.uMouseTarget (Vec3 from raycaster on PlaneZ=0)',
    '- fragmentShader: distance fade + couleur primaire glowing',
    '- Le pointer attire les particules a la souris -> effet futuriste signature',
    '',
    'Option E — Scanline retro CRT post-processing (recommande pour brand vintage / gaming):',
    '- EffectComposer + RenderPass + custom ShaderPass:',
    '  fragmentShader vec2 sl = vec2(uv.x, mod(uv.y * 240.0 + time * 5.0, 1.0)); col *= 0.92 + 0.08 * sin(uv.y * 600.0)',
    '- Donne un look CRT TV vintage immersif.',
    '',
    '### POST-PROCESSING OBLIGATOIRE (au moins UnrealBloomPass)',
    '- import { EffectComposer } from "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/EffectComposer.js"',
    '- import { RenderPass } from ".../examples/jsm/postprocessing/RenderPass.js"',
    '- import { UnrealBloomPass } from ".../examples/jsm/postprocessing/UnrealBloomPass.js"',
    '- import { OutputPass } from ".../examples/jsm/postprocessing/OutputPass.js"',
    '- Bloom config: threshold:0.65, strength:0.85, radius:0.5 — fait briller la couleur primaire sans flouter le produit.',
    '- composer.setPixelRatio(min(devicePixelRatio, 2)); composer.setSize(w, h)',
    '- Boucle render: composer.render() au lieu de renderer.render() — sinon le bloom ne s applique pas.',
    '',
    '### EFFETS COMPLEMENTAIRES (NICE TO HAVE pour pousser au-dela du basique)',
    '- DOF / Bokeh: BokehPass(scene, camera, {focus:5, aperture:0.0008, maxblur:0.012}) — focus piqu sur le produit, arriere-plan flou cinematic.',
    '- Vignette: customShaderPass avec vec2 d=uv-0.5; col*=smoothstep(0.7,0.3,length(d)); — assombrissement bords pour focus central.',
    '- Chromatic aberration au scroll: shifter R/G/B channels par 1-2px sur scrollVelocity > 0.5 — effet glitch dynamique.',
    '- Film grain: ajout sin(rand(uv*time)) * 0.03 sur final color — texture cinema legere.',
    '',
    'OUVERTURE: tu peux composer plusieurs options simultanement (ex: Option A halo Fresnel SUR le produit + Option C gradient background + Bloom). Le but est un rendu qui ressemble a un site Awwwards SOTM, pas a un tutoriel debutant.',
  ],
}

const SAAS_PATTERNS = /\b(saas|abonnement|subscription|pricing|tarif|plan|enterprise|api|platform|productivit|crm|erp|outil pro)\b/i
const PORTFOLIO_PATTERNS = /\b(portfolio|portefeuille|cv|curriculum|developer\s*portfolio|projets|works|showcase|freelance|graphiste|photographe|artiste)\b/i
const ECOMMERCE_PATTERNS = /\b(boutique|shop|magasin|ecommerce|e-commerce|panier|cart|vente|produit|store|catalogue|prix|achat|click and collect)\b/i
const DASHBOARD_PATTERNS = /\b(dashboard|admin|console|analytics|stats|metrics|monitoring|kpi|backoffice|panel|tableau de bord)\b/i
const THREE_D_PATTERNS = /\b(three\.?js|threejs|webgl|webgpu|3d|scene 3d|model 3d|gltf|glb|orbit ?control|rapier|cannon|babylon)\b/i
const GAME_PATTERNS = /\b(jeu|game|arcade|puzzle|platformer|shooter|rpg|tetris|snake|pong|breakout|asteroid|2048|wordle|memory|chess|echecs|score|highscore|level|niveau)\b/i
const MOBILE_PATTERNS = /\b(react native|expo|flutter|mobile app|application mobile|ios app|android app|app smartphone|app telephone)\b/i
const DESKTOP_PATTERNS = /\b(electron|tauri|desktop app|application desktop|app native|windows app|macos app)\b/i

export function detectSubjectVariant(promptText: string): SubjectVariant {
  const lower = promptText.toLowerCase()
  // Order matters: most specific first.
  if (DESKTOP_PATTERNS.test(lower)) return 'desktop'
  if (MOBILE_PATTERNS.test(lower)) return 'mobile'
  if (THREE_D_PATTERNS.test(lower)) return '3d_scene'
  if (GAME_PATTERNS.test(lower)) return 'game'
  if (DASHBOARD_PATTERNS.test(lower)) return 'dashboard'
  if (ECOMMERCE_PATTERNS.test(lower)) return 'ecommerce'
  if (PORTFOLIO_PATTERNS.test(lower)) return 'portfolio'
  if (SAAS_PATTERNS.test(lower)) return 'saas'
  if (/\b(landing|home|accueil|hero)\b/i.test(lower)) return 'landing'
  return null
}
