import JSZip from 'jszip'
import { fsMkdir, fsReadBinary, fsWriteBinary, fsWriteText, getWorkspacePath, ollamaGenerate, toAssetUrl } from '../hooks/useTauri'
import {
  AUXILIARY_ANALYSIS_MODEL,
  resolveConfiguredModel,
} from '../config/models'
import { useAppStore } from '../stores/appStore'
import type { ModuleId } from '../types/app'

export type SaveTarget = 'workspace' | 'zip'

export interface CodeFileEntry {
  name: string
  content: string
}

export interface SaveRequest {
  module: ModuleId
  /** Absolute path to the generated file (video, image, glb, etc.) or sandbox dir (code) */
  sourcePath: string
  prompt: string
  fidelityScore: number
  parameters: Record<string, unknown>
  modelLabel?: string
  /** For code module: the actual project files to save (avoids reading directory as binary) */
  codeFiles?: CodeFileEntry[]
}

export interface SaveResult {
  ok: boolean
  savedPath: string
  zipPath?: string
  error?: string
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
}

function nowLabel(): string {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
}

/**
 * Genere un titre court et semantique a partir du prompt via Ollama.
 * Ex: "une application de gestion de stocks" → "app-gestion-stocks"
 * Fallback: slugify(prompt) si Ollama indisponible.
 */
async function generateSemanticSlug(prompt: string, module: ModuleId): Promise<string> {
  const moduleHints: Record<ModuleId, string> = {
    image: 'image',
    video: 'video',
    drawing: 'dessin',
    '3d': 'modele-3d',
    code: 'app',
    conversation: 'discussion',
    learning: 'cours',
    voice: 'voix',
    cyber: 'cyber',
  }
  const hint = moduleHints[module] || module
  try {
    const { mainModel } = useAppStore.getState()
    const titleModel = resolveConfiguredModel(mainModel, AUXILIARY_ANALYSIS_MODEL)
    const titlePrompt = `/no_think
Generate a short English title (2-4 words max) for this ${hint} based on the prompt below.
Rules:
- Output ONLY the title, nothing else
- Use lowercase, no special characters except hyphens
- Be descriptive of the content, not the prompt itself
- Example: "sunset-beach-portrait" or "fastapi-crud-jwt" or "medieval-castle-3d"

Prompt: ${prompt.slice(0, 200)}`

    const response = await ollamaGenerate(titleModel, titlePrompt)
    const raw = (response?.response || '').trim()
      .replace(/<think>[\s\S]*?<\/think>/g, '')
      .replace(/<think>[\s\S]*$/g, '')
      .trim()
    const cleaned = slugify(raw.split('\n')[0] || '')
    if (cleaned.length >= 4 && cleaned.length <= 52) return cleaned
  } catch {
    // Fallback silencieux
  }
  return slugify(prompt)
}

function buildMetadata(request: SaveRequest, savedPath: string): string {
  return JSON.stringify(
    {
      module: request.module,
      prompt: request.prompt,
      fidelityScore: request.fidelityScore,
      parameters: request.parameters,
      modelLabel: request.modelLabel,
      savedAt: new Date().toISOString(),
      savedPath,
    },
    null,
    2,
  )
}

function buildReadme(request: SaveRequest): string {
  const lines = [
    `# AuroraIA — ${request.module.toUpperCase()} Export`,
    '',
    `**Module**: ${request.module}`,
    `**Fidelity score**: ${request.fidelityScore}/100`,
    `**Model**: ${request.modelLabel ?? 'N/A'}`,
    `**Generated at**: ${new Date().toLocaleString()}`,
    '',
    '## Prompt',
    '',
    request.prompt,
    '',
    '## Parameters',
    '',
    '```json',
    JSON.stringify(request.parameters, null, 2),
    '```',
    '',
    '## Usage',
    '',
    'This export was generated by AuroraIA. To reproduce the result, load the',
    'prompt and parameters above in the corresponding module.',
  ]
  return lines.join('\n')
}

function readStringParameter(parameters: Record<string, unknown>, key: string): string | null {
  const value = parameters[key]
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null
}

function ensureCodeExportFiles(request: SaveRequest): CodeFileEntry[] | undefined {
  if (!request.codeFiles || request.codeFiles.length === 0) return request.codeFiles

  const existingFiles = [...request.codeFiles]
  const normalizedNames = existingFiles.map((file) => file.name.replace(/\\/g, '/').toLowerCase())
  if (normalizedNames.includes('lancement.bat')) return existingFiles

  const projectType = readStringParameter(request.parameters, 'projectType')
  const devCommand = readStringParameter(request.parameters, 'devCommand')
  const hasPackageJson = normalizedNames.some((name) => name.endsWith('package.json'))
  const hasRequirements = normalizedNames.includes('requirements.txt')
  const hasIndexHtml = normalizedNames.includes('index.html')
  const pythonEntry = existingFiles.find((file) => /(^|\/)(main|app)\.py$/i.test(file.name.replace(/\\/g, '/')))

  let content: string | null = null

  if ((projectType === 'static_web' || hasIndexHtml) && !hasPackageJson) {
    content = [
      '@echo off',
      'setlocal',
      'cd /d "%~dp0"',
      'if exist "index.html" (',
      '  start "" "index.html"',
      ') else (',
      '  echo index.html introuvable dans ce dossier.',
      '  pause',
      '  exit /b 1',
      ')',
      'endlocal',
    ].join('\n')
  } else if (hasPackageJson) {
    const runCommand = devCommand || 'npm run dev'
    content = [
      '@echo off',
      'setlocal',
      'cd /d "%~dp0"',
      'where npm >nul 2>nul',
      'if errorlevel 1 (',
      '  echo Node.js avec npm est requis pour ce projet.',
      '  pause',
      '  exit /b 1',
      ')',
      'if not exist "node_modules" (',
      '  echo Installation des dependances...',
      '  call npm install',
      '  if errorlevel 1 (',
      '    echo Echec de npm install.',
      '    pause',
      '    exit /b 1',
      '  )',
      ')',
      `call ${runCommand}`,
      'set "EXITCODE=%ERRORLEVEL%"',
      'if not "%EXITCODE%"=="0" pause',
      'endlocal & exit /b %EXITCODE%',
    ].join('\n')
  } else if (hasRequirements || pythonEntry) {
    const entry = pythonEntry?.name || 'main.py'
    const installLines = hasRequirements
      ? [
          'echo Installation des dependances Python...',
          'call python -m pip install -r requirements.txt',
          'if errorlevel 1 (',
          '  echo Echec de l installation Python.',
          '  pause',
          '  exit /b 1',
          ')',
        ]
      : []
    content = [
      '@echo off',
      'setlocal',
      'cd /d "%~dp0"',
      'where python >nul 2>nul',
      'if errorlevel 1 (',
      '  echo Python est requis pour ce projet.',
      '  pause',
      '  exit /b 1',
      ')',
      ...installLines,
      `call python ${entry}`,
      'set "EXITCODE=%ERRORLEVEL%"',
      'if not "%EXITCODE%"=="0" pause',
      'endlocal & exit /b %EXITCODE%',
    ].join('\n')
  }

  if (!content) return existingFiles

  return [
    ...existingFiles,
    { name: 'lancement.bat', content },
  ]
}

// ---------------------------------------------------------------------------
// ZIP — proper archive with JSZip containing the output file + metadata
// ---------------------------------------------------------------------------

async function buildZipBlob(saveDir: string, outputExt: string, codeFiles?: CodeFileEntry[]): Promise<Blob> {
  const zip = new JSZip()

  if (codeFiles && codeFiles.length > 0) {
    // Code module: add each project file to the zip
    const projectFolder = zip.folder('project')!
    for (const file of codeFiles) {
      projectFolder.file(file.name, file.content)
    }
  } else {
    // Single file output
    const outputPath = `${saveDir}/output.${outputExt}`
    try {
      const outputBytes = await fsReadBinary(outputPath)
      zip.file(`output.${outputExt}`, new Uint8Array(outputBytes))
    } catch {
      // Output file might not exist yet if called before save
    }
  }

  // Read metadata and README
  try {
    const metaBytes = await fsReadBinary(`${saveDir}/metadata.json`)
    zip.file('metadata.json', new Uint8Array(metaBytes))
  } catch {
    // ignore
  }

  try {
    const readmeBytes = await fsReadBinary(`${saveDir}/README.md`)
    zip.file('README.md', new Uint8Array(readmeBytes))
  } catch {
    // ignore
  }

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } })
}

// Trigger a download using a Blob URL — avoids the Tauri asset:// URL issue
// that causes the webview to go transparent/blank.
function triggerBlobDownload(blob: Blob, filename: string): void {
  const blobUrl = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = blobUrl
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  // Revoke after a short delay so the download can start
  setTimeout(() => URL.revokeObjectURL(blobUrl), 30_000)
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Save a generated result to the workspace. Returns the save directory path. */
export async function saveToWorkspace(request: SaveRequest): Promise<SaveResult> {
  try {
    const workspacePath = await getWorkspacePath()
    const slug = await generateSemanticSlug(request.prompt, request.module)
    const label = `${nowLabel()}-${slug}`
    const saveDir = `${workspacePath}/saves/${request.module}/${label}`
    const codeFiles = ensureCodeExportFiles(request)

    await fsMkdir(saveDir)

    if (codeFiles && codeFiles.length > 0) {
      // Code module: write each project file individually into a project/ subdirectory
      const projectDir = `${saveDir}/project`
      await fsMkdir(projectDir)
      for (const file of codeFiles) {
        // Handle nested paths (e.g. src/index.ts)
        const filePath = `${projectDir}/${file.name}`
        const parentDir = filePath.substring(0, filePath.lastIndexOf('/'))
        if (parentDir !== projectDir) {
          await fsMkdir(parentDir)
        }
        await fsWriteText(filePath, file.content)
      }
    } else {
      // Single file output (image, video, 3D, etc.)
      const ext = request.sourcePath.split('.').pop() ?? 'bin'
      const destFile = `${saveDir}/output.${ext}`
      const bytes = await fsReadBinary(request.sourcePath)
      await fsWriteBinary(destFile, bytes)
    }

    // Write metadata
    await fsWriteText(`${saveDir}/metadata.json`, buildMetadata(request, saveDir))
    await fsWriteText(`${saveDir}/README.md`, buildReadme(request))

    return { ok: true, savedPath: saveDir }
  } catch (error) {
    return { ok: false, savedPath: '', error: String(error) }
  }
}

/** Export a save directory as a ZIP file and trigger download. */
export async function exportAsZip(saveDir: string, promptSlug: string, outputExt?: string, codeFiles?: CodeFileEntry[]): Promise<SaveResult> {
  try {
    const ext = outputExt ?? 'bin'
    const zipBlob = await buildZipBlob(saveDir, ext, codeFiles)

    // Write the ZIP to disk as well (optional, for local access)
    const zipPath = `${saveDir}/${promptSlug}.zip`
    const zipBytes = Array.from(new Uint8Array(await zipBlob.arrayBuffer()))
    await fsWriteBinary(zipPath, zipBytes)

    try {
      const { isTauriRuntime } = await import('../utils/runtime.ts')
      if (isTauriRuntime()) {
        const { save } = await import('@tauri-apps/plugin-dialog')
        const filePath = await save({
          defaultPath: `${promptSlug}.zip`,
          filters: [{ name: 'Archive ZIP', extensions: ['zip'] }]
        })
        
        if (filePath) {
          await fsWriteBinary(filePath, zipBytes)
          return { ok: true, savedPath: filePath, zipPath: filePath }
        } else {
          return { ok: false, savedPath: saveDir, error: "Sauvegarde annulée par l'utilisateur." }
        }
      }
    } catch (err) {
      console.warn("Dialog plugin not available or error:", err)
    }

    // Fallback if not Tauri or if dialog failed
    triggerBlobDownload(zipBlob, `${promptSlug}.zip`)

    return { ok: true, savedPath: saveDir, zipPath }
  } catch (error) {
    return { ok: false, savedPath: saveDir, error: String(error) }
  }
}

/** Save the generated result AND export as ZIP in one call. */
export async function saveAndExportZip(request: SaveRequest): Promise<SaveResult> {
  const workspaceResult = await saveToWorkspace(request)
  if (!workspaceResult.ok) return workspaceResult
  // Extraire le slug depuis le chemin sauvegarde (deja genere semantiquement)
  const savedDirName = workspaceResult.savedPath.split('/').pop() || ''
  const slug = savedDirName.replace(/^\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-/, '') || slugify(request.prompt)
  const codeFiles = ensureCodeExportFiles(request)
  const ext = codeFiles ? undefined : request.sourcePath.split('.').pop()
  return exportAsZip(workspaceResult.savedPath, slug, ext, codeFiles)
}
