import { describe, test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { CODE_ARCHITECTURE_PLAN_SCHEMA_VERSION } from '../services/codeArchitecturePlan.ts'
import { executeCodeGenerationQueue } from '../services/codeGenerationExecutor.ts'
import { buildGenerationQueueFromArchitecturePlan } from '../services/codeGenerationQueue.ts'
import type { CodeFile } from '../services/codeOrchestrator.ts'

const ENTITY_NAMES = [
  'customers', 'teams', 'projects', 'tasks', 'invoices', 'payments', 'plans', 'subscriptions',
  'tickets', 'comments', 'notifications', 'auditEvents', 'apiKeys', 'webhooks', 'documents',
  'folders', 'dashboards', 'widgets', 'reports', 'segments', 'campaigns', 'leads', 'deals',
  'products', 'prices', 'warehouses', 'shipments', 'integrations', 'workflows', 'approvals',
  'roles', 'members',
]

function nextMetaFactory() {
  let sequence = 0
  return () => ({ runId: 40, sequence: ++sequence, timestamp: 1_700_000_040_000 + sequence })
}

function pascalCase(name: string) {
  return name.replace(/(^|[A-Z])([a-z])/g, (_match, prefix, letter) => `${prefix ? letter.toUpperCase() : letter.toUpperCase()}`)
}

function languageForPath(path: string) {
  if (path.endsWith('.json')) return 'json'
  if (path.endsWith('.md')) return 'markdown'
  if (path.endsWith('.mjs')) return 'javascript'
  return 'text'
}

function entityModule(name: string) {
  const factory = `create${pascalCase(name)}`
  return `export const entity = {
  name: '${name}',
  label: '${name.replace(/[A-Z]/g, (c) => ` ${c.toLowerCase()}`)}',
  fields: ['id', 'name', 'status', 'ownerId', 'createdAt'],
  seed: [{ id: '${name}-seed', name: '${name} seed', status: 'active', ownerId: 'u-admin' }],
}

export function ${factory}(overrides = {}) {
  return {
    id: '${name}-1',
    name: '${name} demo',
    status: 'active',
    ownerId: 'u-admin',
    createdAt: '2026-07-15T00:00:00.000Z',
    ...overrides,
  }
}
`
}

function buildProofFiles() {
  const files = new Map<string, string>()
  files.set('package.json', JSON.stringify({
    name: 'aurora-ws3-large-saas-proof',
    private: true,
    type: 'module',
    scripts: {
      build: 'node scripts/build-check.mjs',
      test: 'node tests/run-tests.mjs',
    },
  }, null, 2) + '\n')
  files.set('README.md', '# Aurora WS3 large SaaS proof\n\nGenerated by the WS3 planner-executor proof test.\n')
  files.set('src/auth/hash.mjs', `import { createHash } from 'node:crypto'
export function hashPassword(password, salt = 'aurora') {
  return createHash('sha256').update(\`\${salt}:\${password}\`).digest('hex')
}
`)
  files.set('src/auth/passwordPolicy.mjs', `export function assertStrongPassword(password) {
  if (typeof password !== 'string' || password.length < 10) throw new Error('password_too_short')
  if (!/[A-Z]/.test(password) || !/[0-9]/.test(password)) throw new Error('password_too_weak')
  return true
}
`)
  files.set('src/auth/token.mjs', `export function createToken(user) {
  return Buffer.from(JSON.stringify({ sub: user.id, role: user.role })).toString('base64url')
}
export function parseToken(token) {
  return JSON.parse(Buffer.from(token, 'base64url').toString('utf8'))
}
`)
  files.set('src/auth/sessionStore.mjs', `export function createSessionStore() {
  const sessions = new Map()
  return {
    create(user, token) { const session = { id: \`sess-\${sessions.size + 1}\`, user, token }; sessions.set(session.id, session); return session },
    get(id) { return sessions.get(id) ?? null },
    count() { return sessions.size },
  }
}
`)
  files.set('src/auth/permissions.mjs', `const ROLE_PERMISSIONS = {
  admin: ['project:write', 'project:read', 'billing:read'],
  member: ['project:read'],
}
export function can(role, permission) {
  return (ROLE_PERMISSIONS[role] ?? []).includes(permission)
}
`)
  files.set('src/auth/authService.mjs', `import { hashPassword } from './hash.mjs'
import { assertStrongPassword } from './passwordPolicy.mjs'
import { createToken } from './token.mjs'
import { createSessionStore } from './sessionStore.mjs'
import { can } from './permissions.mjs'

export function createAuthService() {
  const users = new Map()
  const sessions = createSessionStore()
  return {
    register({ id, email, password, role = 'member' }) {
      assertStrongPassword(password)
      const user = { id, email, role, passwordHash: hashPassword(password) }
      users.set(email, user)
      return user
    },
    login(email, password) {
      const user = users.get(email)
      if (!user || user.passwordHash !== hashPassword(password)) throw new Error('invalid_credentials')
      const token = createToken(user)
      return { user, token, session: sessions.create(user, token) }
    },
    can(session, permission) { return can(session.user.role, permission) },
    sessionCount() { return sessions.count() },
  }
}
`)
  files.set('src/crud/memoryDb.mjs', `export function createMemoryDb() {
  const tables = new Map()
  const table = (name) => { if (!tables.has(name)) tables.set(name, new Map()); return tables.get(name) }
  return {
    insert(entity, record) { table(entity).set(record.id, record); return record },
    list(entity) { return [...table(entity).values()] },
    update(entity, id, patch) { const next = { ...table(entity).get(id), ...patch }; table(entity).set(id, next); return next },
    remove(entity, id) { return table(entity).delete(id) },
    count(entity) { return table(entity).size },
  }
}
`)
  files.set('src/crud/validators.mjs', `export function validateRecord(entity, record) {
  if (!record || typeof record !== 'object') throw new Error(\`\${entity.name}:record_invalid\`)
  for (const field of ['id', 'name', 'status']) {
    if (typeof record[field] !== 'string' || record[field].length === 0) throw new Error(\`\${entity.name}:\${field}_missing\`)
  }
  return true
}
`)
  files.set('src/crud/repositoryFactory.mjs', `export function createRepository(db, entity) {
  return {
    create(record) { return db.insert(entity.name, record) },
    list() { return db.list(entity.name) },
    update(id, patch) { return db.update(entity.name, id, patch) },
    remove(id) { return db.remove(entity.name, id) },
    count() { return db.count(entity.name) },
  }
}
`)
  files.set('src/crud/serviceFactory.mjs', `import { createRepository } from './repositoryFactory.mjs'
import { validateRecord } from './validators.mjs'
export function createCrudService(db, entity) {
  const repo = createRepository(db, entity)
  return {
    create(input) { const record = { status: 'active', ...input }; validateRecord(entity, record); return repo.create(record) },
    list: repo.list,
    update: repo.update,
    remove: repo.remove,
    count: repo.count,
  }
}
`)
  files.set('src/crud/auditLog.mjs', `export function createAuditLog() {
  const events = []
  return { push(event) { events.push({ at: new Date(0).toISOString(), ...event }) }, list() { return events.slice() } }
}
`)

  for (const name of ENTITY_NAMES) files.set(`src/entities/${name}.mjs`, entityModule(name))

  const imports = ENTITY_NAMES.map((name, index) => `import { entity as entity${index} } from './${name}.mjs'`).join('\n')
  files.set('src/entities/index.mjs', `${imports}
export const entities = [${ENTITY_NAMES.map((_name, index) => `entity${index}`).join(', ')}]
export const entityNames = entities.map((entity) => entity.name)
`)
  files.set('src/index.mjs', `import { createAuthService } from './auth/authService.mjs'
import { createMemoryDb } from './crud/memoryDb.mjs'
import { createCrudService } from './crud/serviceFactory.mjs'
import { entities, entityNames } from './entities/index.mjs'

export { entities, entityNames }
export function createApp() {
  const db = createMemoryDb()
  const services = Object.fromEntries(entities.map((entity) => [entity.name, createCrudService(db, entity)]))
  return { auth: createAuthService(), services, entityNames }
}
`)
  files.set('scripts/build-check.mjs', `import { createApp, entities } from '../src/index.mjs'
const app = createApp()
if (entities.length < 32) throw new Error('entity_count_too_low')
for (const entity of entities) {
  const record = app.services[entity.name].create({ id: \`\${entity.name}-build\`, name: entity.name, status: 'active' })
  if (!record.id) throw new Error(\`\${entity.name}:create_failed\`)
}
console.log(\`build-check ok \${entities.length} entities\`)
`)
  files.set('tests/auth.test.mjs', `import assert from 'node:assert/strict'
import { createApp } from '../src/index.mjs'

export function runAuthTest() {
  const app = createApp()
  app.auth.register({ id: 'u-admin', email: 'admin@aurora.test', password: 'StrongPass1', role: 'admin' })
  const login = app.auth.login('admin@aurora.test', 'StrongPass1')
  assert.equal(app.auth.can(login.session, 'project:write'), true)
  assert.equal(app.auth.sessionCount(), 1)
  return 'auth register/login/permissions'
}
`)
  files.set('tests/crud.test.mjs', `import assert from 'node:assert/strict'
import { createApp } from '../src/index.mjs'

export function runCrudTest() {
  const app = createApp()
  assert.equal(app.entityNames.length >= 32, true)
  const customer = app.services.customers.create({ id: 'c1', name: 'Acme', status: 'active' })
  assert.equal(customer.name, 'Acme')
  assert.equal(app.services.customers.count(), 1)
  assert.equal(app.services.customers.update('c1', { status: 'paused' }).status, 'paused')
  assert.equal(app.services.customers.remove('c1'), true)
  return 'crud services cover all generated entities'
}
`)
  files.set('tests/run-tests.mjs', `import { runAuthTest } from './auth.test.mjs'
import { runCrudTest } from './crud.test.mjs'
const results = [runAuthTest(), runCrudTest()]
for (const result of results) console.log(result)
console.log(\`tests ok \${results.length}\`)
`)
  return files
}

function architecturePlanFor(files: Map<string, string>) {
  const paths = [...files.keys()]
  return JSON.stringify({
    schemaVersion: CODE_ARCHITECTURE_PLAN_SCHEMA_VERSION,
    projectType: 'saas_mini',
    summary: 'Mini SaaS autonome avec authentification, CRUD multi-entites et tests Node reels.',
    stack: {
      runtime: 'node',
      packageManager: 'npm',
      languages: ['JavaScript'],
      frameworks: ['Node test runner'],
      dependencies: [],
      scripts: [
        { name: 'build', command: 'npm run build', purpose: 'verification executable' },
        { name: 'test', command: 'npm test', purpose: 'tests auth et CRUD' },
      ],
    },
    files: paths.map((path) => ({
      path,
      role: path.startsWith('src/entities/') ? 'entity module' : 'application file',
      language: languageForPath(path),
      required: true,
      imports: [],
      exports: [],
      notes: [],
    })),
    dataFlow: ['auth service -> session -> CRUD services -> memory DB'],
    execution: {
      install: [],
      dev: ['node src/index.mjs'],
      build: ['npm run build'],
      test: ['npm test'],
      preview: 'node scripts/build-check.mjs',
    },
    generationOrder: paths,
    validation: ['plus de 40 fichiers', 'npm run build vert', 'npm test vert'],
    risks: [{ risk: 'generation tronquee', mitigation: 'executor fichier par fichier + test build reel' }],
    design: { palette: ['system'], typography: ['system'], ux: ['api-first'], responsive: ['not-applicable'] },
  })
}

async function writeProject(root: string, files: CodeFile[]) {
  for (const file of files) {
    const target = join(root, file.name)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, file.content, 'utf8')
  }
}

describe('codeAgenticLargeProjectProof', () => {
  test('executor WS3 genere un mini SaaS >40 fichiers buildable et teste', async () => {
    const proofFiles = buildProofFiles()
    const queue = buildGenerationQueueFromArchitecturePlan(architecturePlanFor(proofFiles))
    assert.ok(queue)
    assert.equal(queue.items.length > 40, true)

    const result = await executeCodeGenerationQueue({
      queue,
      nextMeta: nextMetaFactory(),
      produceActions: async ({ item }) => {
        const content = proofFiles.get(item.path)
        assert.equal(typeof content, 'string')
        return [{ kind: 'write_file', path: item.path, language: item.language ?? undefined, content }]
      },
    })

    assert.equal(result.ok, true)
    assert.equal(result.files.length, proofFiles.size)
    assert.equal(result.files.length > 40, true)
    assert.equal(result.events.at(-1)?.kind, 'done')

    const root = await mkdtemp(join(tmpdir(), 'aurora-ws3-large-proof-'))
    try {
      await writeProject(root, result.files)
      const build = execFileSync('npm', ['run', 'build', '--silent'], { cwd: root, encoding: 'utf8', timeout: 20_000 })
      const tests = execFileSync('npm', ['test', '--silent'], { cwd: root, encoding: 'utf8', timeout: 20_000 })
      assert.match(build, /build-check ok 32 entities/)
      assert.match(tests, /auth register\/login\/permissions/)
      assert.match(tests, /crud services cover all generated entities/)
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })
})
